// Code generated by go-swagger; DO NOT EDIT.

package my_leaves

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewMyLeavesReadParams creates a new MyLeavesReadParams object
// with the default values initialized.
func NewMyLeavesReadParams() *MyLeavesReadParams {
	var ()
	return &MyLeavesReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMyLeavesReadParamsWithTimeout creates a new MyLeavesReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMyLeavesReadParamsWithTimeout(timeout time.Duration) *MyLeavesReadParams {
	var ()
	return &MyLeavesReadParams{

		timeout: timeout,
	}
}

// NewMyLeavesReadParamsWithContext creates a new MyLeavesReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewMyLeavesReadParamsWithContext(ctx context.Context) *MyLeavesReadParams {
	var ()
	return &MyLeavesReadParams{

		Context: ctx,
	}
}

// NewMyLeavesReadParamsWithHTTPClient creates a new MyLeavesReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMyLeavesReadParamsWithHTTPClient(client *http.Client) *MyLeavesReadParams {
	var ()
	return &MyLeavesReadParams{
		HTTPClient: client,
	}
}

/*MyLeavesReadParams contains all the parameters to send to the API endpoint
for the my leaves read operation typically these are written to a http.Request
*/
type MyLeavesReadParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the my leaves read params
func (o *MyLeavesReadParams) WithTimeout(timeout time.Duration) *MyLeavesReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the my leaves read params
func (o *MyLeavesReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the my leaves read params
func (o *MyLeavesReadParams) WithContext(ctx context.Context) *MyLeavesReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the my leaves read params
func (o *MyLeavesReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the my leaves read params
func (o *MyLeavesReadParams) WithHTTPClient(client *http.Client) *MyLeavesReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the my leaves read params
func (o *MyLeavesReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the my leaves read params
func (o *MyLeavesReadParams) WithID(id string) *MyLeavesReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the my leaves read params
func (o *MyLeavesReadParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *MyLeavesReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
