// Code generated by go-swagger; DO NOT EDIT.

package my_leaves

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// MyLeavesCreateReader is a Reader for the MyLeavesCreate structure.
type MyLeavesCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MyLeavesCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewMyLeavesCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewMyLeavesCreateCreated creates a MyLeavesCreateCreated with default headers values
func NewMyLeavesCreateCreated() *MyLeavesCreateCreated {
	return &MyLeavesCreateCreated{}
}

/*MyLeavesCreateCreated handles this case with default header values.

MyLeavesCreateCreated my leaves create created
*/
type MyLeavesCreateCreated struct {
}

func (o *MyLeavesCreateCreated) Error() string {
	return fmt.Sprintf("[POST /api/v1/my_leaves/][%d] myLeavesCreateCreated ", 201)
}

func (o *MyLeavesCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*MyLeavesCreateBody my leaves create body
swagger:model MyLeavesCreateBody
*/

type MyLeavesCreateBody struct {

	// attachments
	Attachments []string `json:"attachments"`

	// description
	Description string `json:"description,omitempty"`

	// leave type
	// Required: true
	LeaveType *string `json:"leave_type"`

	// status
	// Required: true
	Status *string `json:"status"`
}

/* polymorph MyLeavesCreateBody attachments false */

/* polymorph MyLeavesCreateBody description false */

/* polymorph MyLeavesCreateBody leave_type false */

/* polymorph MyLeavesCreateBody status false */

// MarshalBinary interface implementation
func (o *MyLeavesCreateBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *MyLeavesCreateBody) UnmarshalBinary(b []byte) error {
	var res MyLeavesCreateBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
