// Code generated by go-swagger; DO NOT EDIT.

package leaves

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLeavesReadParams creates a new LeavesReadParams object
// with the default values initialized.
func NewLeavesReadParams() *LeavesReadParams {
	var ()
	return &LeavesReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLeavesReadParamsWithTimeout creates a new LeavesReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLeavesReadParamsWithTimeout(timeout time.Duration) *LeavesReadParams {
	var ()
	return &LeavesReadParams{

		timeout: timeout,
	}
}

// NewLeavesReadParamsWithContext creates a new LeavesReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewLeavesReadParamsWithContext(ctx context.Context) *LeavesReadParams {
	var ()
	return &LeavesReadParams{

		Context: ctx,
	}
}

// NewLeavesReadParamsWithHTTPClient creates a new LeavesReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewLeavesReadParamsWithHTTPClient(client *http.Client) *LeavesReadParams {
	var ()
	return &LeavesReadParams{
		HTTPClient: client,
	}
}

/*LeavesReadParams contains all the parameters to send to the API endpoint
for the leaves read operation typically these are written to a http.Request
*/
type LeavesReadParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the leaves read params
func (o *LeavesReadParams) WithTimeout(timeout time.Duration) *LeavesReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the leaves read params
func (o *LeavesReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the leaves read params
func (o *LeavesReadParams) WithContext(ctx context.Context) *LeavesReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the leaves read params
func (o *LeavesReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the leaves read params
func (o *LeavesReadParams) WithHTTPClient(client *http.Client) *LeavesReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the leaves read params
func (o *LeavesReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the leaves read params
func (o *LeavesReadParams) WithID(id string) *LeavesReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the leaves read params
func (o *LeavesReadParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *LeavesReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
