// Code generated by go-swagger; DO NOT EDIT.

package leaves

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new leaves API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for leaves API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
LeavesList APIs endpoint that allows leaves to be viewed or edited

API endpoint that allows leaves to be viewed or edited.
*/
func (a *Client) LeavesList(params *LeavesListParams, authInfo runtime.ClientAuthInfoWriter) (*LeavesListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewLeavesListParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "leaves_list",
		Method:             "GET",
		PathPattern:        "/api/v1/leaves/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &LeavesListReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*LeavesListOK), nil

}

/*
LeavesRead APIs endpoint that allows leaves to be viewed or edited

API endpoint that allows leaves to be viewed or edited.
*/
func (a *Client) LeavesRead(params *LeavesReadParams, authInfo runtime.ClientAuthInfoWriter) (*LeavesReadOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewLeavesReadParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "leaves_read",
		Method:             "GET",
		PathPattern:        "/api/v1/leaves/{id}/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &LeavesReadReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*LeavesReadOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
