// Code generated by go-swagger; DO NOT EDIT.

package my_timesheets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewMyTimesheetsUpdateParams creates a new MyTimesheetsUpdateParams object
// with the default values initialized.
func NewMyTimesheetsUpdateParams() *MyTimesheetsUpdateParams {
	var ()
	return &MyTimesheetsUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMyTimesheetsUpdateParamsWithTimeout creates a new MyTimesheetsUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMyTimesheetsUpdateParamsWithTimeout(timeout time.Duration) *MyTimesheetsUpdateParams {
	var ()
	return &MyTimesheetsUpdateParams{

		timeout: timeout,
	}
}

// NewMyTimesheetsUpdateParamsWithContext creates a new MyTimesheetsUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewMyTimesheetsUpdateParamsWithContext(ctx context.Context) *MyTimesheetsUpdateParams {
	var ()
	return &MyTimesheetsUpdateParams{

		Context: ctx,
	}
}

// NewMyTimesheetsUpdateParamsWithHTTPClient creates a new MyTimesheetsUpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMyTimesheetsUpdateParamsWithHTTPClient(client *http.Client) *MyTimesheetsUpdateParams {
	var ()
	return &MyTimesheetsUpdateParams{
		HTTPClient: client,
	}
}

/*MyTimesheetsUpdateParams contains all the parameters to send to the API endpoint
for the my timesheets update operation typically these are written to a http.Request
*/
type MyTimesheetsUpdateParams struct {

	/*Data*/
	Data MyTimesheetsUpdateBody
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the my timesheets update params
func (o *MyTimesheetsUpdateParams) WithTimeout(timeout time.Duration) *MyTimesheetsUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the my timesheets update params
func (o *MyTimesheetsUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the my timesheets update params
func (o *MyTimesheetsUpdateParams) WithContext(ctx context.Context) *MyTimesheetsUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the my timesheets update params
func (o *MyTimesheetsUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the my timesheets update params
func (o *MyTimesheetsUpdateParams) WithHTTPClient(client *http.Client) *MyTimesheetsUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the my timesheets update params
func (o *MyTimesheetsUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the my timesheets update params
func (o *MyTimesheetsUpdateParams) WithData(data MyTimesheetsUpdateBody) *MyTimesheetsUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the my timesheets update params
func (o *MyTimesheetsUpdateParams) SetData(data MyTimesheetsUpdateBody) {
	o.Data = data
}

// WithID adds the id to the my timesheets update params
func (o *MyTimesheetsUpdateParams) WithID(id string) *MyTimesheetsUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the my timesheets update params
func (o *MyTimesheetsUpdateParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *MyTimesheetsUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
