// Code generated by go-swagger; DO NOT EDIT.

package my_timesheets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// MyTimesheetsReadReader is a Reader for the MyTimesheetsRead structure.
type MyTimesheetsReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MyTimesheetsReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewMyTimesheetsReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewMyTimesheetsReadOK creates a MyTimesheetsReadOK with default headers values
func NewMyTimesheetsReadOK() *MyTimesheetsReadOK {
	return &MyTimesheetsReadOK{}
}

/*MyTimesheetsReadOK handles this case with default header values.

MyTimesheetsReadOK my timesheets read o k
*/
type MyTimesheetsReadOK struct {
}

func (o *MyTimesheetsReadOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/my_timesheets/{id}/][%d] myTimesheetsReadOK ", 200)
}

func (o *MyTimesheetsReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
