// Code generated by go-swagger; DO NOT EDIT.

package my_timesheets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewMyTimesheetsDeleteParams creates a new MyTimesheetsDeleteParams object
// with the default values initialized.
func NewMyTimesheetsDeleteParams() *MyTimesheetsDeleteParams {
	var ()
	return &MyTimesheetsDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMyTimesheetsDeleteParamsWithTimeout creates a new MyTimesheetsDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMyTimesheetsDeleteParamsWithTimeout(timeout time.Duration) *MyTimesheetsDeleteParams {
	var ()
	return &MyTimesheetsDeleteParams{

		timeout: timeout,
	}
}

// NewMyTimesheetsDeleteParamsWithContext creates a new MyTimesheetsDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewMyTimesheetsDeleteParamsWithContext(ctx context.Context) *MyTimesheetsDeleteParams {
	var ()
	return &MyTimesheetsDeleteParams{

		Context: ctx,
	}
}

// NewMyTimesheetsDeleteParamsWithHTTPClient creates a new MyTimesheetsDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMyTimesheetsDeleteParamsWithHTTPClient(client *http.Client) *MyTimesheetsDeleteParams {
	var ()
	return &MyTimesheetsDeleteParams{
		HTTPClient: client,
	}
}

/*MyTimesheetsDeleteParams contains all the parameters to send to the API endpoint
for the my timesheets delete operation typically these are written to a http.Request
*/
type MyTimesheetsDeleteParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the my timesheets delete params
func (o *MyTimesheetsDeleteParams) WithTimeout(timeout time.Duration) *MyTimesheetsDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the my timesheets delete params
func (o *MyTimesheetsDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the my timesheets delete params
func (o *MyTimesheetsDeleteParams) WithContext(ctx context.Context) *MyTimesheetsDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the my timesheets delete params
func (o *MyTimesheetsDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the my timesheets delete params
func (o *MyTimesheetsDeleteParams) WithHTTPClient(client *http.Client) *MyTimesheetsDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the my timesheets delete params
func (o *MyTimesheetsDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the my timesheets delete params
func (o *MyTimesheetsDeleteParams) WithID(id string) *MyTimesheetsDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the my timesheets delete params
func (o *MyTimesheetsDeleteParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *MyTimesheetsDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
