// Code generated by go-swagger; DO NOT EDIT.

package my_timesheets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// MyTimesheetsDeleteReader is a Reader for the MyTimesheetsDelete structure.
type MyTimesheetsDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MyTimesheetsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewMyTimesheetsDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewMyTimesheetsDeleteNoContent creates a MyTimesheetsDeleteNoContent with default headers values
func NewMyTimesheetsDeleteNoContent() *MyTimesheetsDeleteNoContent {
	return &MyTimesheetsDeleteNoContent{}
}

/*MyTimesheetsDeleteNoContent handles this case with default header values.

MyTimesheetsDeleteNoContent my timesheets delete no content
*/
type MyTimesheetsDeleteNoContent struct {
}

func (o *MyTimesheetsDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/my_timesheets/{id}/][%d] myTimesheetsDeleteNoContent ", 204)
}

func (o *MyTimesheetsDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
