// Code generated by go-swagger; DO NOT EDIT.

package my_timesheets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewMyTimesheetsReadParams creates a new MyTimesheetsReadParams object
// with the default values initialized.
func NewMyTimesheetsReadParams() *MyTimesheetsReadParams {
	var ()
	return &MyTimesheetsReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMyTimesheetsReadParamsWithTimeout creates a new MyTimesheetsReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMyTimesheetsReadParamsWithTimeout(timeout time.Duration) *MyTimesheetsReadParams {
	var ()
	return &MyTimesheetsReadParams{

		timeout: timeout,
	}
}

// NewMyTimesheetsReadParamsWithContext creates a new MyTimesheetsReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewMyTimesheetsReadParamsWithContext(ctx context.Context) *MyTimesheetsReadParams {
	var ()
	return &MyTimesheetsReadParams{

		Context: ctx,
	}
}

// NewMyTimesheetsReadParamsWithHTTPClient creates a new MyTimesheetsReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMyTimesheetsReadParamsWithHTTPClient(client *http.Client) *MyTimesheetsReadParams {
	var ()
	return &MyTimesheetsReadParams{
		HTTPClient: client,
	}
}

/*MyTimesheetsReadParams contains all the parameters to send to the API endpoint
for the my timesheets read operation typically these are written to a http.Request
*/
type MyTimesheetsReadParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the my timesheets read params
func (o *MyTimesheetsReadParams) WithTimeout(timeout time.Duration) *MyTimesheetsReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the my timesheets read params
func (o *MyTimesheetsReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the my timesheets read params
func (o *MyTimesheetsReadParams) WithContext(ctx context.Context) *MyTimesheetsReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the my timesheets read params
func (o *MyTimesheetsReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the my timesheets read params
func (o *MyTimesheetsReadParams) WithHTTPClient(client *http.Client) *MyTimesheetsReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the my timesheets read params
func (o *MyTimesheetsReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the my timesheets read params
func (o *MyTimesheetsReadParams) WithID(id string) *MyTimesheetsReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the my timesheets read params
func (o *MyTimesheetsReadParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *MyTimesheetsReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
