// Code generated by go-swagger; DO NOT EDIT.

package my_timesheets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewMyTimesheetsCreateParams creates a new MyTimesheetsCreateParams object
// with the default values initialized.
func NewMyTimesheetsCreateParams() *MyTimesheetsCreateParams {
	var ()
	return &MyTimesheetsCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMyTimesheetsCreateParamsWithTimeout creates a new MyTimesheetsCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMyTimesheetsCreateParamsWithTimeout(timeout time.Duration) *MyTimesheetsCreateParams {
	var ()
	return &MyTimesheetsCreateParams{

		timeout: timeout,
	}
}

// NewMyTimesheetsCreateParamsWithContext creates a new MyTimesheetsCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewMyTimesheetsCreateParamsWithContext(ctx context.Context) *MyTimesheetsCreateParams {
	var ()
	return &MyTimesheetsCreateParams{

		Context: ctx,
	}
}

// NewMyTimesheetsCreateParamsWithHTTPClient creates a new MyTimesheetsCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMyTimesheetsCreateParamsWithHTTPClient(client *http.Client) *MyTimesheetsCreateParams {
	var ()
	return &MyTimesheetsCreateParams{
		HTTPClient: client,
	}
}

/*MyTimesheetsCreateParams contains all the parameters to send to the API endpoint
for the my timesheets create operation typically these are written to a http.Request
*/
type MyTimesheetsCreateParams struct {

	/*Data*/
	Data MyTimesheetsCreateBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the my timesheets create params
func (o *MyTimesheetsCreateParams) WithTimeout(timeout time.Duration) *MyTimesheetsCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the my timesheets create params
func (o *MyTimesheetsCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the my timesheets create params
func (o *MyTimesheetsCreateParams) WithContext(ctx context.Context) *MyTimesheetsCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the my timesheets create params
func (o *MyTimesheetsCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the my timesheets create params
func (o *MyTimesheetsCreateParams) WithHTTPClient(client *http.Client) *MyTimesheetsCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the my timesheets create params
func (o *MyTimesheetsCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the my timesheets create params
func (o *MyTimesheetsCreateParams) WithData(data MyTimesheetsCreateBody) *MyTimesheetsCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the my timesheets create params
func (o *MyTimesheetsCreateParams) SetData(data MyTimesheetsCreateBody) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *MyTimesheetsCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
