// Code generated by go-swagger; DO NOT EDIT.

package my_timesheets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// MyTimesheetsUpdateReader is a Reader for the MyTimesheetsUpdate structure.
type MyTimesheetsUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MyTimesheetsUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewMyTimesheetsUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewMyTimesheetsUpdateOK creates a MyTimesheetsUpdateOK with default headers values
func NewMyTimesheetsUpdateOK() *MyTimesheetsUpdateOK {
	return &MyTimesheetsUpdateOK{}
}

/*MyTimesheetsUpdateOK handles this case with default header values.

MyTimesheetsUpdateOK my timesheets update o k
*/
type MyTimesheetsUpdateOK struct {
}

func (o *MyTimesheetsUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /api/v1/my_timesheets/{id}/][%d] myTimesheetsUpdateOK ", 200)
}

func (o *MyTimesheetsUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*MyTimesheetsUpdateBody my timesheets update body
swagger:model MyTimesheetsUpdateBody
*/

type MyTimesheetsUpdateBody struct {

	// month
	// Required: true
	Month *int64 `json:"month"`

	// status
	Status string `json:"status,omitempty"`

	// year
	// Required: true
	Year *int64 `json:"year"`
}

/* polymorph MyTimesheetsUpdateBody month false */

/* polymorph MyTimesheetsUpdateBody status false */

/* polymorph MyTimesheetsUpdateBody year false */

// MarshalBinary interface implementation
func (o *MyTimesheetsUpdateBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *MyTimesheetsUpdateBody) UnmarshalBinary(b []byte) error {
	var res MyTimesheetsUpdateBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
