// Code generated by go-swagger; DO NOT EDIT.

package contracts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ContractsProjectListReader is a Reader for the ContractsProjectList structure.
type ContractsProjectListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ContractsProjectListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewContractsProjectListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewContractsProjectListOK creates a ContractsProjectListOK with default headers values
func NewContractsProjectListOK() *ContractsProjectListOK {
	return &ContractsProjectListOK{}
}

/*ContractsProjectListOK handles this case with default header values.

ContractsProjectListOK contracts project list o k
*/
type ContractsProjectListOK struct {
}

func (o *ContractsProjectListOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/contracts/project/][%d] contractsProjectListOK ", 200)
}

func (o *ContractsProjectListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
