// Code generated by go-swagger; DO NOT EDIT.

package contracts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ContractsConsultancyReadReader is a Reader for the ContractsConsultancyRead structure.
type ContractsConsultancyReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ContractsConsultancyReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewContractsConsultancyReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewContractsConsultancyReadOK creates a ContractsConsultancyReadOK with default headers values
func NewContractsConsultancyReadOK() *ContractsConsultancyReadOK {
	return &ContractsConsultancyReadOK{}
}

/*ContractsConsultancyReadOK handles this case with default header values.

ContractsConsultancyReadOK contracts consultancy read o k
*/
type ContractsConsultancyReadOK struct {
}

func (o *ContractsConsultancyReadOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/contracts/consultancy/{id}/][%d] contractsConsultancyReadOK ", 200)
}

func (o *ContractsConsultancyReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
