// Code generated by go-swagger; DO NOT EDIT.

package contracts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ContractsSupportListReader is a Reader for the ContractsSupportList structure.
type ContractsSupportListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ContractsSupportListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewContractsSupportListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewContractsSupportListOK creates a ContractsSupportListOK with default headers values
func NewContractsSupportListOK() *ContractsSupportListOK {
	return &ContractsSupportListOK{}
}

/*ContractsSupportListOK handles this case with default header values.

ContractsSupportListOK contracts support list o k
*/
type ContractsSupportListOK struct {
}

func (o *ContractsSupportListOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/contracts/support/][%d] contractsSupportListOK ", 200)
}

func (o *ContractsSupportListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
