// Code generated by go-swagger; DO NOT EDIT.

package contracts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewContractsReadParams creates a new ContractsReadParams object
// with the default values initialized.
func NewContractsReadParams() *ContractsReadParams {
	var ()
	return &ContractsReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewContractsReadParamsWithTimeout creates a new ContractsReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewContractsReadParamsWithTimeout(timeout time.Duration) *ContractsReadParams {
	var ()
	return &ContractsReadParams{

		timeout: timeout,
	}
}

// NewContractsReadParamsWithContext creates a new ContractsReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewContractsReadParamsWithContext(ctx context.Context) *ContractsReadParams {
	var ()
	return &ContractsReadParams{

		Context: ctx,
	}
}

// NewContractsReadParamsWithHTTPClient creates a new ContractsReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewContractsReadParamsWithHTTPClient(client *http.Client) *ContractsReadParams {
	var ()
	return &ContractsReadParams{
		HTTPClient: client,
	}
}

/*ContractsReadParams contains all the parameters to send to the API endpoint
for the contracts read operation typically these are written to a http.Request
*/
type ContractsReadParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the contracts read params
func (o *ContractsReadParams) WithTimeout(timeout time.Duration) *ContractsReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the contracts read params
func (o *ContractsReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the contracts read params
func (o *ContractsReadParams) WithContext(ctx context.Context) *ContractsReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the contracts read params
func (o *ContractsReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the contracts read params
func (o *ContractsReadParams) WithHTTPClient(client *http.Client) *ContractsReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the contracts read params
func (o *ContractsReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the contracts read params
func (o *ContractsReadParams) WithID(id string) *ContractsReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the contracts read params
func (o *ContractsReadParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ContractsReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
