// Code generated by go-swagger; DO NOT EDIT.

package performances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPerformancesStandbyReadParams creates a new PerformancesStandbyReadParams object
// with the default values initialized.
func NewPerformancesStandbyReadParams() *PerformancesStandbyReadParams {
	var ()
	return &PerformancesStandbyReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPerformancesStandbyReadParamsWithTimeout creates a new PerformancesStandbyReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPerformancesStandbyReadParamsWithTimeout(timeout time.Duration) *PerformancesStandbyReadParams {
	var ()
	return &PerformancesStandbyReadParams{

		timeout: timeout,
	}
}

// NewPerformancesStandbyReadParamsWithContext creates a new PerformancesStandbyReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewPerformancesStandbyReadParamsWithContext(ctx context.Context) *PerformancesStandbyReadParams {
	var ()
	return &PerformancesStandbyReadParams{

		Context: ctx,
	}
}

// NewPerformancesStandbyReadParamsWithHTTPClient creates a new PerformancesStandbyReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPerformancesStandbyReadParamsWithHTTPClient(client *http.Client) *PerformancesStandbyReadParams {
	var ()
	return &PerformancesStandbyReadParams{
		HTTPClient: client,
	}
}

/*PerformancesStandbyReadParams contains all the parameters to send to the API endpoint
for the performances standby read operation typically these are written to a http.Request
*/
type PerformancesStandbyReadParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the performances standby read params
func (o *PerformancesStandbyReadParams) WithTimeout(timeout time.Duration) *PerformancesStandbyReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the performances standby read params
func (o *PerformancesStandbyReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the performances standby read params
func (o *PerformancesStandbyReadParams) WithContext(ctx context.Context) *PerformancesStandbyReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the performances standby read params
func (o *PerformancesStandbyReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the performances standby read params
func (o *PerformancesStandbyReadParams) WithHTTPClient(client *http.Client) *PerformancesStandbyReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the performances standby read params
func (o *PerformancesStandbyReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the performances standby read params
func (o *PerformancesStandbyReadParams) WithID(id string) *PerformancesStandbyReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the performances standby read params
func (o *PerformancesStandbyReadParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PerformancesStandbyReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
