// Code generated by go-swagger; DO NOT EDIT.

package user_relatives

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// UserRelativesListReader is a Reader for the UserRelativesList structure.
type UserRelativesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserRelativesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUserRelativesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUserRelativesListOK creates a UserRelativesListOK with default headers values
func NewUserRelativesListOK() *UserRelativesListOK {
	return &UserRelativesListOK{}
}

/*UserRelativesListOK handles this case with default header values.

UserRelativesListOK user relatives list o k
*/
type UserRelativesListOK struct {
}

func (o *UserRelativesListOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/user_relatives/][%d] userRelativesListOK ", 200)
}

func (o *UserRelativesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
