// Code generated by go-swagger; DO NOT EDIT.

package user_relatives

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new user relatives API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for user relatives API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
UserRelativesList APIs endpoint that allows user relatives to be viewed or edited

API endpoint that allows user relatives to be viewed or edited.
*/
func (a *Client) UserRelativesList(params *UserRelativesListParams, authInfo runtime.ClientAuthInfoWriter) (*UserRelativesListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUserRelativesListParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "user_relatives_list",
		Method:             "GET",
		PathPattern:        "/api/v1/user_relatives/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &UserRelativesListReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*UserRelativesListOK), nil

}

/*
UserRelativesRead APIs endpoint that allows user relatives to be viewed or edited

API endpoint that allows user relatives to be viewed or edited.
*/
func (a *Client) UserRelativesRead(params *UserRelativesReadParams, authInfo runtime.ClientAuthInfoWriter) (*UserRelativesReadOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUserRelativesReadParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "user_relatives_read",
		Method:             "GET",
		PathPattern:        "/api/v1/user_relatives/{id}/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &UserRelativesReadReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*UserRelativesReadOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
