// Code generated by go-swagger; DO NOT EDIT.

package performance_types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPerformanceTypesReadParams creates a new PerformanceTypesReadParams object
// with the default values initialized.
func NewPerformanceTypesReadParams() *PerformanceTypesReadParams {
	var ()
	return &PerformanceTypesReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPerformanceTypesReadParamsWithTimeout creates a new PerformanceTypesReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPerformanceTypesReadParamsWithTimeout(timeout time.Duration) *PerformanceTypesReadParams {
	var ()
	return &PerformanceTypesReadParams{

		timeout: timeout,
	}
}

// NewPerformanceTypesReadParamsWithContext creates a new PerformanceTypesReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewPerformanceTypesReadParamsWithContext(ctx context.Context) *PerformanceTypesReadParams {
	var ()
	return &PerformanceTypesReadParams{

		Context: ctx,
	}
}

// NewPerformanceTypesReadParamsWithHTTPClient creates a new PerformanceTypesReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPerformanceTypesReadParamsWithHTTPClient(client *http.Client) *PerformanceTypesReadParams {
	var ()
	return &PerformanceTypesReadParams{
		HTTPClient: client,
	}
}

/*PerformanceTypesReadParams contains all the parameters to send to the API endpoint
for the performance types read operation typically these are written to a http.Request
*/
type PerformanceTypesReadParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the performance types read params
func (o *PerformanceTypesReadParams) WithTimeout(timeout time.Duration) *PerformanceTypesReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the performance types read params
func (o *PerformanceTypesReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the performance types read params
func (o *PerformanceTypesReadParams) WithContext(ctx context.Context) *PerformanceTypesReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the performance types read params
func (o *PerformanceTypesReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the performance types read params
func (o *PerformanceTypesReadParams) WithHTTPClient(client *http.Client) *PerformanceTypesReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the performance types read params
func (o *PerformanceTypesReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the performance types read params
func (o *PerformanceTypesReadParams) WithID(id string) *PerformanceTypesReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the performance types read params
func (o *PerformanceTypesReadParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PerformanceTypesReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
