// Code generated by go-swagger; DO NOT EDIT.

package performance_types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PerformanceTypesListReader is a Reader for the PerformanceTypesList structure.
type PerformanceTypesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PerformanceTypesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPerformanceTypesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPerformanceTypesListOK creates a PerformanceTypesListOK with default headers values
func NewPerformanceTypesListOK() *PerformanceTypesListOK {
	return &PerformanceTypesListOK{}
}

/*PerformanceTypesListOK handles this case with default header values.

PerformanceTypesListOK performance types list o k
*/
type PerformanceTypesListOK struct {
}

func (o *PerformanceTypesListOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/performance_types/][%d] performanceTypesListOK ", 200)
}

func (o *PerformanceTypesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
