// Code generated by go-swagger; DO NOT EDIT.

package performance_types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new performance types API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for performance types API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
PerformanceTypesList APIs endpoint that allows performance types to be viewed or edited

API endpoint that allows performance types to be viewed or edited.
*/
func (a *Client) PerformanceTypesList(params *PerformanceTypesListParams, authInfo runtime.ClientAuthInfoWriter) (*PerformanceTypesListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPerformanceTypesListParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "performance_types_list",
		Method:             "GET",
		PathPattern:        "/api/v1/performance_types/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PerformanceTypesListReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PerformanceTypesListOK), nil

}

/*
PerformanceTypesRead APIs endpoint that allows performance types to be viewed or edited

API endpoint that allows performance types to be viewed or edited.
*/
func (a *Client) PerformanceTypesRead(params *PerformanceTypesReadParams, authInfo runtime.ClientAuthInfoWriter) (*PerformanceTypesReadOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPerformanceTypesReadParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "performance_types_read",
		Method:             "GET",
		PathPattern:        "/api/v1/performance_types/{id}/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PerformanceTypesReadReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PerformanceTypesReadOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
