// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new groups API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for groups API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GroupsList APIs endpoint that allows groups to be viewed or edited

API endpoint that allows groups to be viewed or edited.
*/
func (a *Client) GroupsList(params *GroupsListParams, authInfo runtime.ClientAuthInfoWriter) (*GroupsListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGroupsListParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "groups_list",
		Method:             "GET",
		PathPattern:        "/api/v1/groups/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GroupsListReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GroupsListOK), nil

}

/*
GroupsRead APIs endpoint that allows groups to be viewed or edited

API endpoint that allows groups to be viewed or edited.
*/
func (a *Client) GroupsRead(params *GroupsReadParams, authInfo runtime.ClientAuthInfoWriter) (*GroupsReadOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGroupsReadParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "groups_read",
		Method:             "GET",
		PathPattern:        "/api/v1/groups/{id}/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GroupsReadReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GroupsReadOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
