// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GroupsReadReader is a Reader for the GroupsRead structure.
type GroupsReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GroupsReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGroupsReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGroupsReadOK creates a GroupsReadOK with default headers values
func NewGroupsReadOK() *GroupsReadOK {
	return &GroupsReadOK{}
}

/*GroupsReadOK handles this case with default header values.

GroupsReadOK groups read o k
*/
type GroupsReadOK struct {
}

func (o *GroupsReadOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/groups/{id}/][%d] groupsReadOK ", 200)
}

func (o *GroupsReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
