// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GroupsListReader is a Reader for the GroupsList structure.
type GroupsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GroupsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGroupsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGroupsListOK creates a GroupsListOK with default headers values
func NewGroupsListOK() *GroupsListOK {
	return &GroupsListOK{}
}

/*GroupsListOK handles this case with default header values.

GroupsListOK groups list o k
*/
type GroupsListOK struct {
}

func (o *GroupsListOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/groups/][%d] groupsListOK ", 200)
}

func (o *GroupsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
