// Code generated by go-swagger; DO NOT EDIT.

package my_leave_dates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewMyLeaveDatesCreateParams creates a new MyLeaveDatesCreateParams object
// with the default values initialized.
func NewMyLeaveDatesCreateParams() *MyLeaveDatesCreateParams {
	var ()
	return &MyLeaveDatesCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMyLeaveDatesCreateParamsWithTimeout creates a new MyLeaveDatesCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMyLeaveDatesCreateParamsWithTimeout(timeout time.Duration) *MyLeaveDatesCreateParams {
	var ()
	return &MyLeaveDatesCreateParams{

		timeout: timeout,
	}
}

// NewMyLeaveDatesCreateParamsWithContext creates a new MyLeaveDatesCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewMyLeaveDatesCreateParamsWithContext(ctx context.Context) *MyLeaveDatesCreateParams {
	var ()
	return &MyLeaveDatesCreateParams{

		Context: ctx,
	}
}

// NewMyLeaveDatesCreateParamsWithHTTPClient creates a new MyLeaveDatesCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMyLeaveDatesCreateParamsWithHTTPClient(client *http.Client) *MyLeaveDatesCreateParams {
	var ()
	return &MyLeaveDatesCreateParams{
		HTTPClient: client,
	}
}

/*MyLeaveDatesCreateParams contains all the parameters to send to the API endpoint
for the my leave dates create operation typically these are written to a http.Request
*/
type MyLeaveDatesCreateParams struct {

	/*Data*/
	Data MyLeaveDatesCreateBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the my leave dates create params
func (o *MyLeaveDatesCreateParams) WithTimeout(timeout time.Duration) *MyLeaveDatesCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the my leave dates create params
func (o *MyLeaveDatesCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the my leave dates create params
func (o *MyLeaveDatesCreateParams) WithContext(ctx context.Context) *MyLeaveDatesCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the my leave dates create params
func (o *MyLeaveDatesCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the my leave dates create params
func (o *MyLeaveDatesCreateParams) WithHTTPClient(client *http.Client) *MyLeaveDatesCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the my leave dates create params
func (o *MyLeaveDatesCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the my leave dates create params
func (o *MyLeaveDatesCreateParams) WithData(data MyLeaveDatesCreateBody) *MyLeaveDatesCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the my leave dates create params
func (o *MyLeaveDatesCreateParams) SetData(data MyLeaveDatesCreateBody) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *MyLeaveDatesCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
