// Code generated by go-swagger; DO NOT EDIT.

package my_leave_dates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// MyLeaveDatesUpdateReader is a Reader for the MyLeaveDatesUpdate structure.
type MyLeaveDatesUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MyLeaveDatesUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewMyLeaveDatesUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewMyLeaveDatesUpdateOK creates a MyLeaveDatesUpdateOK with default headers values
func NewMyLeaveDatesUpdateOK() *MyLeaveDatesUpdateOK {
	return &MyLeaveDatesUpdateOK{}
}

/*MyLeaveDatesUpdateOK handles this case with default header values.

MyLeaveDatesUpdateOK my leave dates update o k
*/
type MyLeaveDatesUpdateOK struct {
}

func (o *MyLeaveDatesUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /api/v1/my_leave_dates/{id}/][%d] myLeaveDatesUpdateOK ", 200)
}

func (o *MyLeaveDatesUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*MyLeaveDatesUpdateBody my leave dates update body
swagger:model MyLeaveDatesUpdateBody
*/

type MyLeaveDatesUpdateBody struct {

	// ends at
	// Required: true
	EndsAt *string `json:"ends_at"`

	// leave
	// Required: true
	Leave *string `json:"leave"`

	// starts at
	// Required: true
	StartsAt *string `json:"starts_at"`

	// timesheet
	// Required: true
	Timesheet *string `json:"timesheet"`
}

/* polymorph MyLeaveDatesUpdateBody ends_at false */

/* polymorph MyLeaveDatesUpdateBody leave false */

/* polymorph MyLeaveDatesUpdateBody starts_at false */

/* polymorph MyLeaveDatesUpdateBody timesheet false */

// MarshalBinary interface implementation
func (o *MyLeaveDatesUpdateBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *MyLeaveDatesUpdateBody) UnmarshalBinary(b []byte) error {
	var res MyLeaveDatesUpdateBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
