// Code generated by go-swagger; DO NOT EDIT.

package my_leave_dates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewMyLeaveDatesDeleteParams creates a new MyLeaveDatesDeleteParams object
// with the default values initialized.
func NewMyLeaveDatesDeleteParams() *MyLeaveDatesDeleteParams {
	var ()
	return &MyLeaveDatesDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMyLeaveDatesDeleteParamsWithTimeout creates a new MyLeaveDatesDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMyLeaveDatesDeleteParamsWithTimeout(timeout time.Duration) *MyLeaveDatesDeleteParams {
	var ()
	return &MyLeaveDatesDeleteParams{

		timeout: timeout,
	}
}

// NewMyLeaveDatesDeleteParamsWithContext creates a new MyLeaveDatesDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewMyLeaveDatesDeleteParamsWithContext(ctx context.Context) *MyLeaveDatesDeleteParams {
	var ()
	return &MyLeaveDatesDeleteParams{

		Context: ctx,
	}
}

// NewMyLeaveDatesDeleteParamsWithHTTPClient creates a new MyLeaveDatesDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMyLeaveDatesDeleteParamsWithHTTPClient(client *http.Client) *MyLeaveDatesDeleteParams {
	var ()
	return &MyLeaveDatesDeleteParams{
		HTTPClient: client,
	}
}

/*MyLeaveDatesDeleteParams contains all the parameters to send to the API endpoint
for the my leave dates delete operation typically these are written to a http.Request
*/
type MyLeaveDatesDeleteParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the my leave dates delete params
func (o *MyLeaveDatesDeleteParams) WithTimeout(timeout time.Duration) *MyLeaveDatesDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the my leave dates delete params
func (o *MyLeaveDatesDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the my leave dates delete params
func (o *MyLeaveDatesDeleteParams) WithContext(ctx context.Context) *MyLeaveDatesDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the my leave dates delete params
func (o *MyLeaveDatesDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the my leave dates delete params
func (o *MyLeaveDatesDeleteParams) WithHTTPClient(client *http.Client) *MyLeaveDatesDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the my leave dates delete params
func (o *MyLeaveDatesDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the my leave dates delete params
func (o *MyLeaveDatesDeleteParams) WithID(id string) *MyLeaveDatesDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the my leave dates delete params
func (o *MyLeaveDatesDeleteParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *MyLeaveDatesDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
