// Code generated by go-swagger; DO NOT EDIT.

package my_leave_dates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// MyLeaveDatesListReader is a Reader for the MyLeaveDatesList structure.
type MyLeaveDatesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MyLeaveDatesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewMyLeaveDatesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewMyLeaveDatesListOK creates a MyLeaveDatesListOK with default headers values
func NewMyLeaveDatesListOK() *MyLeaveDatesListOK {
	return &MyLeaveDatesListOK{}
}

/*MyLeaveDatesListOK handles this case with default header values.

MyLeaveDatesListOK my leave dates list o k
*/
type MyLeaveDatesListOK struct {
}

func (o *MyLeaveDatesListOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/my_leave_dates/][%d] myLeaveDatesListOK ", 200)
}

func (o *MyLeaveDatesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
