// Code generated by go-swagger; DO NOT EDIT.

package project_estimates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new project estimates API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for project estimates API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
ProjectEstimatesList APIs endpoint that allows project estimates to be viewed or edited

API endpoint that allows project estimates to be viewed or edited.
*/
func (a *Client) ProjectEstimatesList(params *ProjectEstimatesListParams, authInfo runtime.ClientAuthInfoWriter) (*ProjectEstimatesListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewProjectEstimatesListParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "project_estimates_list",
		Method:             "GET",
		PathPattern:        "/api/v1/project_estimates/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ProjectEstimatesListReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ProjectEstimatesListOK), nil

}

/*
ProjectEstimatesRead APIs endpoint that allows project estimates to be viewed or edited

API endpoint that allows project estimates to be viewed or edited.
*/
func (a *Client) ProjectEstimatesRead(params *ProjectEstimatesReadParams, authInfo runtime.ClientAuthInfoWriter) (*ProjectEstimatesReadOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewProjectEstimatesReadParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "project_estimates_read",
		Method:             "GET",
		PathPattern:        "/api/v1/project_estimates/{id}/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ProjectEstimatesReadReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ProjectEstimatesReadOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
