// Code generated by go-swagger; DO NOT EDIT.

package timesheets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// TimesheetsListReader is a Reader for the TimesheetsList structure.
type TimesheetsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TimesheetsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewTimesheetsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewTimesheetsListOK creates a TimesheetsListOK with default headers values
func NewTimesheetsListOK() *TimesheetsListOK {
	return &TimesheetsListOK{}
}

/*TimesheetsListOK handles this case with default header values.

TimesheetsListOK timesheets list o k
*/
type TimesheetsListOK struct {
}

func (o *TimesheetsListOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/timesheets/][%d] timesheetsListOK ", 200)
}

func (o *TimesheetsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
