// Code generated by go-swagger; DO NOT EDIT.

package attachments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new attachments API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for attachments API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
AttachmentsList APIs endpoint that allows attachments to be viewed or edited

API endpoint that allows attachments to be viewed or edited.
*/
func (a *Client) AttachmentsList(params *AttachmentsListParams, authInfo runtime.ClientAuthInfoWriter) (*AttachmentsListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAttachmentsListParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "attachments_list",
		Method:             "GET",
		PathPattern:        "/api/v1/attachments/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &AttachmentsListReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*AttachmentsListOK), nil

}

/*
AttachmentsRead APIs endpoint that allows attachments to be viewed or edited

API endpoint that allows attachments to be viewed or edited.
*/
func (a *Client) AttachmentsRead(params *AttachmentsReadParams, authInfo runtime.ClientAuthInfoWriter) (*AttachmentsReadOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAttachmentsReadParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "attachments_read",
		Method:             "GET",
		PathPattern:        "/api/v1/attachments/{id}/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &AttachmentsReadReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*AttachmentsReadOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
