// Code generated by go-swagger; DO NOT EDIT.

package attachments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAttachmentsReadParams creates a new AttachmentsReadParams object
// with the default values initialized.
func NewAttachmentsReadParams() *AttachmentsReadParams {
	var ()
	return &AttachmentsReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAttachmentsReadParamsWithTimeout creates a new AttachmentsReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAttachmentsReadParamsWithTimeout(timeout time.Duration) *AttachmentsReadParams {
	var ()
	return &AttachmentsReadParams{

		timeout: timeout,
	}
}

// NewAttachmentsReadParamsWithContext creates a new AttachmentsReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewAttachmentsReadParamsWithContext(ctx context.Context) *AttachmentsReadParams {
	var ()
	return &AttachmentsReadParams{

		Context: ctx,
	}
}

// NewAttachmentsReadParamsWithHTTPClient creates a new AttachmentsReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAttachmentsReadParamsWithHTTPClient(client *http.Client) *AttachmentsReadParams {
	var ()
	return &AttachmentsReadParams{
		HTTPClient: client,
	}
}

/*AttachmentsReadParams contains all the parameters to send to the API endpoint
for the attachments read operation typically these are written to a http.Request
*/
type AttachmentsReadParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the attachments read params
func (o *AttachmentsReadParams) WithTimeout(timeout time.Duration) *AttachmentsReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the attachments read params
func (o *AttachmentsReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the attachments read params
func (o *AttachmentsReadParams) WithContext(ctx context.Context) *AttachmentsReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the attachments read params
func (o *AttachmentsReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the attachments read params
func (o *AttachmentsReadParams) WithHTTPClient(client *http.Client) *AttachmentsReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the attachments read params
func (o *AttachmentsReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the attachments read params
func (o *AttachmentsReadParams) WithID(id string) *AttachmentsReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the attachments read params
func (o *AttachmentsReadParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *AttachmentsReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
