// Code generated by go-swagger; DO NOT EDIT.

package attachments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAttachmentsListParams creates a new AttachmentsListParams object
// with the default values initialized.
func NewAttachmentsListParams() *AttachmentsListParams {
	var ()
	return &AttachmentsListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAttachmentsListParamsWithTimeout creates a new AttachmentsListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAttachmentsListParamsWithTimeout(timeout time.Duration) *AttachmentsListParams {
	var ()
	return &AttachmentsListParams{

		timeout: timeout,
	}
}

// NewAttachmentsListParamsWithContext creates a new AttachmentsListParams object
// with the default values initialized, and the ability to set a context for a request
func NewAttachmentsListParamsWithContext(ctx context.Context) *AttachmentsListParams {
	var ()
	return &AttachmentsListParams{

		Context: ctx,
	}
}

// NewAttachmentsListParamsWithHTTPClient creates a new AttachmentsListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAttachmentsListParamsWithHTTPClient(client *http.Client) *AttachmentsListParams {
	var ()
	return &AttachmentsListParams{
		HTTPClient: client,
	}
}

/*AttachmentsListParams contains all the parameters to send to the API endpoint
for the attachments list operation typically these are written to a http.Request
*/
type AttachmentsListParams struct {

	/*Description*/
	Description *string
	/*DescriptionContains*/
	DescriptionContains *string
	/*DescriptionIcontains*/
	DescriptionIcontains *string
	/*Label*/
	Label *string
	/*LabelContains*/
	LabelContains *string
	/*LabelIcontains*/
	LabelIcontains *string
	/*OrderBy*/
	OrderBy *string
	/*Page*/
	Page *string
	/*PageSize*/
	PageSize *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the attachments list params
func (o *AttachmentsListParams) WithTimeout(timeout time.Duration) *AttachmentsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the attachments list params
func (o *AttachmentsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the attachments list params
func (o *AttachmentsListParams) WithContext(ctx context.Context) *AttachmentsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the attachments list params
func (o *AttachmentsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the attachments list params
func (o *AttachmentsListParams) WithHTTPClient(client *http.Client) *AttachmentsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the attachments list params
func (o *AttachmentsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDescription adds the description to the attachments list params
func (o *AttachmentsListParams) WithDescription(description *string) *AttachmentsListParams {
	o.SetDescription(description)
	return o
}

// SetDescription adds the description to the attachments list params
func (o *AttachmentsListParams) SetDescription(description *string) {
	o.Description = description
}

// WithDescriptionContains adds the descriptionContains to the attachments list params
func (o *AttachmentsListParams) WithDescriptionContains(descriptionContains *string) *AttachmentsListParams {
	o.SetDescriptionContains(descriptionContains)
	return o
}

// SetDescriptionContains adds the descriptionContains to the attachments list params
func (o *AttachmentsListParams) SetDescriptionContains(descriptionContains *string) {
	o.DescriptionContains = descriptionContains
}

// WithDescriptionIcontains adds the descriptionIcontains to the attachments list params
func (o *AttachmentsListParams) WithDescriptionIcontains(descriptionIcontains *string) *AttachmentsListParams {
	o.SetDescriptionIcontains(descriptionIcontains)
	return o
}

// SetDescriptionIcontains adds the descriptionIcontains to the attachments list params
func (o *AttachmentsListParams) SetDescriptionIcontains(descriptionIcontains *string) {
	o.DescriptionIcontains = descriptionIcontains
}

// WithLabel adds the label to the attachments list params
func (o *AttachmentsListParams) WithLabel(label *string) *AttachmentsListParams {
	o.SetLabel(label)
	return o
}

// SetLabel adds the label to the attachments list params
func (o *AttachmentsListParams) SetLabel(label *string) {
	o.Label = label
}

// WithLabelContains adds the labelContains to the attachments list params
func (o *AttachmentsListParams) WithLabelContains(labelContains *string) *AttachmentsListParams {
	o.SetLabelContains(labelContains)
	return o
}

// SetLabelContains adds the labelContains to the attachments list params
func (o *AttachmentsListParams) SetLabelContains(labelContains *string) {
	o.LabelContains = labelContains
}

// WithLabelIcontains adds the labelIcontains to the attachments list params
func (o *AttachmentsListParams) WithLabelIcontains(labelIcontains *string) *AttachmentsListParams {
	o.SetLabelIcontains(labelIcontains)
	return o
}

// SetLabelIcontains adds the labelIcontains to the attachments list params
func (o *AttachmentsListParams) SetLabelIcontains(labelIcontains *string) {
	o.LabelIcontains = labelIcontains
}

// WithOrderBy adds the orderBy to the attachments list params
func (o *AttachmentsListParams) WithOrderBy(orderBy *string) *AttachmentsListParams {
	o.SetOrderBy(orderBy)
	return o
}

// SetOrderBy adds the orderBy to the attachments list params
func (o *AttachmentsListParams) SetOrderBy(orderBy *string) {
	o.OrderBy = orderBy
}

// WithPage adds the page to the attachments list params
func (o *AttachmentsListParams) WithPage(page *string) *AttachmentsListParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the attachments list params
func (o *AttachmentsListParams) SetPage(page *string) {
	o.Page = page
}

// WithPageSize adds the pageSize to the attachments list params
func (o *AttachmentsListParams) WithPageSize(pageSize *string) *AttachmentsListParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the attachments list params
func (o *AttachmentsListParams) SetPageSize(pageSize *string) {
	o.PageSize = pageSize
}

// WriteToRequest writes these params to a swagger request
func (o *AttachmentsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Description != nil {

		// query param description
		var qrDescription string
		if o.Description != nil {
			qrDescription = *o.Description
		}
		qDescription := qrDescription
		if qDescription != "" {
			if err := r.SetQueryParam("description", qDescription); err != nil {
				return err
			}
		}

	}

	if o.DescriptionContains != nil {

		// query param description__contains
		var qrDescriptionContains string
		if o.DescriptionContains != nil {
			qrDescriptionContains = *o.DescriptionContains
		}
		qDescriptionContains := qrDescriptionContains
		if qDescriptionContains != "" {
			if err := r.SetQueryParam("description__contains", qDescriptionContains); err != nil {
				return err
			}
		}

	}

	if o.DescriptionIcontains != nil {

		// query param description__icontains
		var qrDescriptionIcontains string
		if o.DescriptionIcontains != nil {
			qrDescriptionIcontains = *o.DescriptionIcontains
		}
		qDescriptionIcontains := qrDescriptionIcontains
		if qDescriptionIcontains != "" {
			if err := r.SetQueryParam("description__icontains", qDescriptionIcontains); err != nil {
				return err
			}
		}

	}

	if o.Label != nil {

		// query param label
		var qrLabel string
		if o.Label != nil {
			qrLabel = *o.Label
		}
		qLabel := qrLabel
		if qLabel != "" {
			if err := r.SetQueryParam("label", qLabel); err != nil {
				return err
			}
		}

	}

	if o.LabelContains != nil {

		// query param label__contains
		var qrLabelContains string
		if o.LabelContains != nil {
			qrLabelContains = *o.LabelContains
		}
		qLabelContains := qrLabelContains
		if qLabelContains != "" {
			if err := r.SetQueryParam("label__contains", qLabelContains); err != nil {
				return err
			}
		}

	}

	if o.LabelIcontains != nil {

		// query param label__icontains
		var qrLabelIcontains string
		if o.LabelIcontains != nil {
			qrLabelIcontains = *o.LabelIcontains
		}
		qLabelIcontains := qrLabelIcontains
		if qLabelIcontains != "" {
			if err := r.SetQueryParam("label__icontains", qLabelIcontains); err != nil {
				return err
			}
		}

	}

	if o.OrderBy != nil {

		// query param order_by
		var qrOrderBy string
		if o.OrderBy != nil {
			qrOrderBy = *o.OrderBy
		}
		qOrderBy := qrOrderBy
		if qOrderBy != "" {
			if err := r.SetQueryParam("order_by", qOrderBy); err != nil {
				return err
			}
		}

	}

	if o.Page != nil {

		// query param page
		var qrPage string
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := qrPage
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if o.PageSize != nil {

		// query param page_size
		var qrPageSize string
		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := qrPageSize
		if qPageSize != "" {
			if err := r.SetQueryParam("page_size", qPageSize); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
