// Code generated by go-swagger; DO NOT EDIT.

package work_schedules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// WorkSchedulesReadReader is a Reader for the WorkSchedulesRead structure.
type WorkSchedulesReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WorkSchedulesReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewWorkSchedulesReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewWorkSchedulesReadOK creates a WorkSchedulesReadOK with default headers values
func NewWorkSchedulesReadOK() *WorkSchedulesReadOK {
	return &WorkSchedulesReadOK{}
}

/*WorkSchedulesReadOK handles this case with default header values.

WorkSchedulesReadOK work schedules read o k
*/
type WorkSchedulesReadOK struct {
}

func (o *WorkSchedulesReadOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/work_schedules/{id}/][%d] workSchedulesReadOK ", 200)
}

func (o *WorkSchedulesReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
