// Code generated by go-swagger; DO NOT EDIT.

package contract_roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewContractRolesReadParams creates a new ContractRolesReadParams object
// with the default values initialized.
func NewContractRolesReadParams() *ContractRolesReadParams {
	var ()
	return &ContractRolesReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewContractRolesReadParamsWithTimeout creates a new ContractRolesReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewContractRolesReadParamsWithTimeout(timeout time.Duration) *ContractRolesReadParams {
	var ()
	return &ContractRolesReadParams{

		timeout: timeout,
	}
}

// NewContractRolesReadParamsWithContext creates a new ContractRolesReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewContractRolesReadParamsWithContext(ctx context.Context) *ContractRolesReadParams {
	var ()
	return &ContractRolesReadParams{

		Context: ctx,
	}
}

// NewContractRolesReadParamsWithHTTPClient creates a new ContractRolesReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewContractRolesReadParamsWithHTTPClient(client *http.Client) *ContractRolesReadParams {
	var ()
	return &ContractRolesReadParams{
		HTTPClient: client,
	}
}

/*ContractRolesReadParams contains all the parameters to send to the API endpoint
for the contract roles read operation typically these are written to a http.Request
*/
type ContractRolesReadParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the contract roles read params
func (o *ContractRolesReadParams) WithTimeout(timeout time.Duration) *ContractRolesReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the contract roles read params
func (o *ContractRolesReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the contract roles read params
func (o *ContractRolesReadParams) WithContext(ctx context.Context) *ContractRolesReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the contract roles read params
func (o *ContractRolesReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the contract roles read params
func (o *ContractRolesReadParams) WithHTTPClient(client *http.Client) *ContractRolesReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the contract roles read params
func (o *ContractRolesReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the contract roles read params
func (o *ContractRolesReadParams) WithID(id string) *ContractRolesReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the contract roles read params
func (o *ContractRolesReadParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ContractRolesReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
