// Code generated by go-swagger; DO NOT EDIT.

package contract_roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ContractRolesReadReader is a Reader for the ContractRolesRead structure.
type ContractRolesReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ContractRolesReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewContractRolesReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewContractRolesReadOK creates a ContractRolesReadOK with default headers values
func NewContractRolesReadOK() *ContractRolesReadOK {
	return &ContractRolesReadOK{}
}

/*ContractRolesReadOK handles this case with default header values.

ContractRolesReadOK contract roles read o k
*/
type ContractRolesReadOK struct {
}

func (o *ContractRolesReadOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/contract_roles/{id}/][%d] contractRolesReadOK ", 200)
}

func (o *ContractRolesReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
