// Code generated by go-swagger; DO NOT EDIT.

package employment_contracts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// EmploymentContractsReadReader is a Reader for the EmploymentContractsRead structure.
type EmploymentContractsReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EmploymentContractsReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEmploymentContractsReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewEmploymentContractsReadOK creates a EmploymentContractsReadOK with default headers values
func NewEmploymentContractsReadOK() *EmploymentContractsReadOK {
	return &EmploymentContractsReadOK{}
}

/*EmploymentContractsReadOK handles this case with default header values.

EmploymentContractsReadOK employment contracts read o k
*/
type EmploymentContractsReadOK struct {
}

func (o *EmploymentContractsReadOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/employment_contracts/{id}/][%d] employmentContractsReadOK ", 200)
}

func (o *EmploymentContractsReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
