// Code generated by go-swagger; DO NOT EDIT.

package employment_contracts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewEmploymentContractsReadParams creates a new EmploymentContractsReadParams object
// with the default values initialized.
func NewEmploymentContractsReadParams() *EmploymentContractsReadParams {
	var ()
	return &EmploymentContractsReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEmploymentContractsReadParamsWithTimeout creates a new EmploymentContractsReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEmploymentContractsReadParamsWithTimeout(timeout time.Duration) *EmploymentContractsReadParams {
	var ()
	return &EmploymentContractsReadParams{

		timeout: timeout,
	}
}

// NewEmploymentContractsReadParamsWithContext creates a new EmploymentContractsReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewEmploymentContractsReadParamsWithContext(ctx context.Context) *EmploymentContractsReadParams {
	var ()
	return &EmploymentContractsReadParams{

		Context: ctx,
	}
}

// NewEmploymentContractsReadParamsWithHTTPClient creates a new EmploymentContractsReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEmploymentContractsReadParamsWithHTTPClient(client *http.Client) *EmploymentContractsReadParams {
	var ()
	return &EmploymentContractsReadParams{
		HTTPClient: client,
	}
}

/*EmploymentContractsReadParams contains all the parameters to send to the API endpoint
for the employment contracts read operation typically these are written to a http.Request
*/
type EmploymentContractsReadParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the employment contracts read params
func (o *EmploymentContractsReadParams) WithTimeout(timeout time.Duration) *EmploymentContractsReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the employment contracts read params
func (o *EmploymentContractsReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the employment contracts read params
func (o *EmploymentContractsReadParams) WithContext(ctx context.Context) *EmploymentContractsReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the employment contracts read params
func (o *EmploymentContractsReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the employment contracts read params
func (o *EmploymentContractsReadParams) WithHTTPClient(client *http.Client) *EmploymentContractsReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the employment contracts read params
func (o *EmploymentContractsReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the employment contracts read params
func (o *EmploymentContractsReadParams) WithID(id string) *EmploymentContractsReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the employment contracts read params
func (o *EmploymentContractsReadParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *EmploymentContractsReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
