// Code generated by go-swagger; DO NOT EDIT.

package employment_contract_types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// EmploymentContractTypesReadReader is a Reader for the EmploymentContractTypesRead structure.
type EmploymentContractTypesReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EmploymentContractTypesReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEmploymentContractTypesReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewEmploymentContractTypesReadOK creates a EmploymentContractTypesReadOK with default headers values
func NewEmploymentContractTypesReadOK() *EmploymentContractTypesReadOK {
	return &EmploymentContractTypesReadOK{}
}

/*EmploymentContractTypesReadOK handles this case with default header values.

EmploymentContractTypesReadOK employment contract types read o k
*/
type EmploymentContractTypesReadOK struct {
}

func (o *EmploymentContractTypesReadOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/employment_contract_types/{id}/][%d] employmentContractTypesReadOK ", 200)
}

func (o *EmploymentContractTypesReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
