// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// UsersReadReader is a Reader for the UsersRead structure.
type UsersReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UsersReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUsersReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUsersReadOK creates a UsersReadOK with default headers values
func NewUsersReadOK() *UsersReadOK {
	return &UsersReadOK{}
}

/*UsersReadOK handles this case with default header values.

UsersReadOK users read o k
*/
type UsersReadOK struct {
}

func (o *UsersReadOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/users/{id}/][%d] usersReadOK ", 200)
}

func (o *UsersReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
