// Code generated by go-swagger; DO NOT EDIT.

package my_workschedules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewMyWorkschedulesPartialUpdateParams creates a new MyWorkschedulesPartialUpdateParams object
// with the default values initialized.
func NewMyWorkschedulesPartialUpdateParams() *MyWorkschedulesPartialUpdateParams {
	var ()
	return &MyWorkschedulesPartialUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMyWorkschedulesPartialUpdateParamsWithTimeout creates a new MyWorkschedulesPartialUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMyWorkschedulesPartialUpdateParamsWithTimeout(timeout time.Duration) *MyWorkschedulesPartialUpdateParams {
	var ()
	return &MyWorkschedulesPartialUpdateParams{

		timeout: timeout,
	}
}

// NewMyWorkschedulesPartialUpdateParamsWithContext creates a new MyWorkschedulesPartialUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewMyWorkschedulesPartialUpdateParamsWithContext(ctx context.Context) *MyWorkschedulesPartialUpdateParams {
	var ()
	return &MyWorkschedulesPartialUpdateParams{

		Context: ctx,
	}
}

// NewMyWorkschedulesPartialUpdateParamsWithHTTPClient creates a new MyWorkschedulesPartialUpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMyWorkschedulesPartialUpdateParamsWithHTTPClient(client *http.Client) *MyWorkschedulesPartialUpdateParams {
	var ()
	return &MyWorkschedulesPartialUpdateParams{
		HTTPClient: client,
	}
}

/*MyWorkschedulesPartialUpdateParams contains all the parameters to send to the API endpoint
for the my workschedules partial update operation typically these are written to a http.Request
*/
type MyWorkschedulesPartialUpdateParams struct {

	/*Data*/
	Data MyWorkschedulesPartialUpdateBody
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the my workschedules partial update params
func (o *MyWorkschedulesPartialUpdateParams) WithTimeout(timeout time.Duration) *MyWorkschedulesPartialUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the my workschedules partial update params
func (o *MyWorkschedulesPartialUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the my workschedules partial update params
func (o *MyWorkschedulesPartialUpdateParams) WithContext(ctx context.Context) *MyWorkschedulesPartialUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the my workschedules partial update params
func (o *MyWorkschedulesPartialUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the my workschedules partial update params
func (o *MyWorkschedulesPartialUpdateParams) WithHTTPClient(client *http.Client) *MyWorkschedulesPartialUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the my workschedules partial update params
func (o *MyWorkschedulesPartialUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the my workschedules partial update params
func (o *MyWorkschedulesPartialUpdateParams) WithData(data MyWorkschedulesPartialUpdateBody) *MyWorkschedulesPartialUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the my workschedules partial update params
func (o *MyWorkschedulesPartialUpdateParams) SetData(data MyWorkschedulesPartialUpdateBody) {
	o.Data = data
}

// WithID adds the id to the my workschedules partial update params
func (o *MyWorkschedulesPartialUpdateParams) WithID(id string) *MyWorkschedulesPartialUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the my workschedules partial update params
func (o *MyWorkschedulesPartialUpdateParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *MyWorkschedulesPartialUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
