// Code generated by go-swagger; DO NOT EDIT.

package my_workschedules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// MyWorkschedulesUpdateReader is a Reader for the MyWorkschedulesUpdate structure.
type MyWorkschedulesUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MyWorkschedulesUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewMyWorkschedulesUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewMyWorkschedulesUpdateOK creates a MyWorkschedulesUpdateOK with default headers values
func NewMyWorkschedulesUpdateOK() *MyWorkschedulesUpdateOK {
	return &MyWorkschedulesUpdateOK{}
}

/*MyWorkschedulesUpdateOK handles this case with default header values.

MyWorkschedulesUpdateOK my workschedules update o k
*/
type MyWorkschedulesUpdateOK struct {
}

func (o *MyWorkschedulesUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /api/v1/my_workschedules/{id}/][%d] myWorkschedulesUpdateOK ", 200)
}

func (o *MyWorkschedulesUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*MyWorkschedulesUpdateBody my workschedules update body
swagger:model MyWorkschedulesUpdateBody
*/

type MyWorkschedulesUpdateBody struct {

	// friday
	Friday float64 `json:"friday,omitempty"`

	// label
	// Required: true
	Label *string `json:"label"`

	// monday
	Monday float64 `json:"monday,omitempty"`

	// saturday
	Saturday float64 `json:"saturday,omitempty"`

	// sunday
	Sunday float64 `json:"sunday,omitempty"`

	// thursday
	Thursday float64 `json:"thursday,omitempty"`

	// tuesday
	Tuesday float64 `json:"tuesday,omitempty"`

	// wednesday
	Wednesday float64 `json:"wednesday,omitempty"`
}

/* polymorph MyWorkschedulesUpdateBody friday false */

/* polymorph MyWorkschedulesUpdateBody label false */

/* polymorph MyWorkschedulesUpdateBody monday false */

/* polymorph MyWorkschedulesUpdateBody saturday false */

/* polymorph MyWorkschedulesUpdateBody sunday false */

/* polymorph MyWorkschedulesUpdateBody thursday false */

/* polymorph MyWorkschedulesUpdateBody tuesday false */

/* polymorph MyWorkschedulesUpdateBody wednesday false */

// MarshalBinary interface implementation
func (o *MyWorkschedulesUpdateBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *MyWorkschedulesUpdateBody) UnmarshalBinary(b []byte) error {
	var res MyWorkschedulesUpdateBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
