// Code generated by go-swagger; DO NOT EDIT.

package my_workschedules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// MyWorkschedulesListReader is a Reader for the MyWorkschedulesList structure.
type MyWorkschedulesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MyWorkschedulesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewMyWorkschedulesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewMyWorkschedulesListOK creates a MyWorkschedulesListOK with default headers values
func NewMyWorkschedulesListOK() *MyWorkschedulesListOK {
	return &MyWorkschedulesListOK{}
}

/*MyWorkschedulesListOK handles this case with default header values.

MyWorkschedulesListOK my workschedules list o k
*/
type MyWorkschedulesListOK struct {
}

func (o *MyWorkschedulesListOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/my_workschedules/][%d] myWorkschedulesListOK ", 200)
}

func (o *MyWorkschedulesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
