// Code generated by go-swagger; DO NOT EDIT.

package my_workschedules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewMyWorkschedulesDeleteParams creates a new MyWorkschedulesDeleteParams object
// with the default values initialized.
func NewMyWorkschedulesDeleteParams() *MyWorkschedulesDeleteParams {
	var ()
	return &MyWorkschedulesDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMyWorkschedulesDeleteParamsWithTimeout creates a new MyWorkschedulesDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMyWorkschedulesDeleteParamsWithTimeout(timeout time.Duration) *MyWorkschedulesDeleteParams {
	var ()
	return &MyWorkschedulesDeleteParams{

		timeout: timeout,
	}
}

// NewMyWorkschedulesDeleteParamsWithContext creates a new MyWorkschedulesDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewMyWorkschedulesDeleteParamsWithContext(ctx context.Context) *MyWorkschedulesDeleteParams {
	var ()
	return &MyWorkschedulesDeleteParams{

		Context: ctx,
	}
}

// NewMyWorkschedulesDeleteParamsWithHTTPClient creates a new MyWorkschedulesDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMyWorkschedulesDeleteParamsWithHTTPClient(client *http.Client) *MyWorkschedulesDeleteParams {
	var ()
	return &MyWorkschedulesDeleteParams{
		HTTPClient: client,
	}
}

/*MyWorkschedulesDeleteParams contains all the parameters to send to the API endpoint
for the my workschedules delete operation typically these are written to a http.Request
*/
type MyWorkschedulesDeleteParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the my workschedules delete params
func (o *MyWorkschedulesDeleteParams) WithTimeout(timeout time.Duration) *MyWorkschedulesDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the my workschedules delete params
func (o *MyWorkschedulesDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the my workschedules delete params
func (o *MyWorkschedulesDeleteParams) WithContext(ctx context.Context) *MyWorkschedulesDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the my workschedules delete params
func (o *MyWorkschedulesDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the my workschedules delete params
func (o *MyWorkschedulesDeleteParams) WithHTTPClient(client *http.Client) *MyWorkschedulesDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the my workschedules delete params
func (o *MyWorkschedulesDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the my workschedules delete params
func (o *MyWorkschedulesDeleteParams) WithID(id string) *MyWorkschedulesDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the my workschedules delete params
func (o *MyWorkschedulesDeleteParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *MyWorkschedulesDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
