// Code generated by go-swagger; DO NOT EDIT.

package my_workschedules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// MyWorkschedulesReadReader is a Reader for the MyWorkschedulesRead structure.
type MyWorkschedulesReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MyWorkschedulesReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewMyWorkschedulesReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewMyWorkschedulesReadOK creates a MyWorkschedulesReadOK with default headers values
func NewMyWorkschedulesReadOK() *MyWorkschedulesReadOK {
	return &MyWorkschedulesReadOK{}
}

/*MyWorkschedulesReadOK handles this case with default header values.

MyWorkschedulesReadOK my workschedules read o k
*/
type MyWorkschedulesReadOK struct {
}

func (o *MyWorkschedulesReadOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/my_workschedules/{id}/][%d] myWorkschedulesReadOK ", 200)
}

func (o *MyWorkschedulesReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
