// Code generated by go-swagger; DO NOT EDIT.

package my_workschedules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewMyWorkschedulesCreateParams creates a new MyWorkschedulesCreateParams object
// with the default values initialized.
func NewMyWorkschedulesCreateParams() *MyWorkschedulesCreateParams {
	var ()
	return &MyWorkschedulesCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMyWorkschedulesCreateParamsWithTimeout creates a new MyWorkschedulesCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMyWorkschedulesCreateParamsWithTimeout(timeout time.Duration) *MyWorkschedulesCreateParams {
	var ()
	return &MyWorkschedulesCreateParams{

		timeout: timeout,
	}
}

// NewMyWorkschedulesCreateParamsWithContext creates a new MyWorkschedulesCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewMyWorkschedulesCreateParamsWithContext(ctx context.Context) *MyWorkschedulesCreateParams {
	var ()
	return &MyWorkschedulesCreateParams{

		Context: ctx,
	}
}

// NewMyWorkschedulesCreateParamsWithHTTPClient creates a new MyWorkschedulesCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMyWorkschedulesCreateParamsWithHTTPClient(client *http.Client) *MyWorkschedulesCreateParams {
	var ()
	return &MyWorkschedulesCreateParams{
		HTTPClient: client,
	}
}

/*MyWorkschedulesCreateParams contains all the parameters to send to the API endpoint
for the my workschedules create operation typically these are written to a http.Request
*/
type MyWorkschedulesCreateParams struct {

	/*Data*/
	Data MyWorkschedulesCreateBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the my workschedules create params
func (o *MyWorkschedulesCreateParams) WithTimeout(timeout time.Duration) *MyWorkschedulesCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the my workschedules create params
func (o *MyWorkschedulesCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the my workschedules create params
func (o *MyWorkschedulesCreateParams) WithContext(ctx context.Context) *MyWorkschedulesCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the my workschedules create params
func (o *MyWorkschedulesCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the my workschedules create params
func (o *MyWorkschedulesCreateParams) WithHTTPClient(client *http.Client) *MyWorkschedulesCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the my workschedules create params
func (o *MyWorkschedulesCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the my workschedules create params
func (o *MyWorkschedulesCreateParams) WithData(data MyWorkschedulesCreateBody) *MyWorkschedulesCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the my workschedules create params
func (o *MyWorkschedulesCreateParams) SetData(data MyWorkschedulesCreateBody) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *MyWorkschedulesCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
