// Code generated by go-swagger; DO NOT EDIT.

package user_infos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// UserInfosListReader is a Reader for the UserInfosList structure.
type UserInfosListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserInfosListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUserInfosListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUserInfosListOK creates a UserInfosListOK with default headers values
func NewUserInfosListOK() *UserInfosListOK {
	return &UserInfosListOK{}
}

/*UserInfosListOK handles this case with default header values.

UserInfosListOK user infos list o k
*/
type UserInfosListOK struct {
}

func (o *UserInfosListOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/user_infos/][%d] userInfosListOK ", 200)
}

func (o *UserInfosListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
