// Code generated by go-swagger; DO NOT EDIT.

package my_contracts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewMyContractsReadParams creates a new MyContractsReadParams object
// with the default values initialized.
func NewMyContractsReadParams() *MyContractsReadParams {
	var ()
	return &MyContractsReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMyContractsReadParamsWithTimeout creates a new MyContractsReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMyContractsReadParamsWithTimeout(timeout time.Duration) *MyContractsReadParams {
	var ()
	return &MyContractsReadParams{

		timeout: timeout,
	}
}

// NewMyContractsReadParamsWithContext creates a new MyContractsReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewMyContractsReadParamsWithContext(ctx context.Context) *MyContractsReadParams {
	var ()
	return &MyContractsReadParams{

		Context: ctx,
	}
}

// NewMyContractsReadParamsWithHTTPClient creates a new MyContractsReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMyContractsReadParamsWithHTTPClient(client *http.Client) *MyContractsReadParams {
	var ()
	return &MyContractsReadParams{
		HTTPClient: client,
	}
}

/*MyContractsReadParams contains all the parameters to send to the API endpoint
for the my contracts read operation typically these are written to a http.Request
*/
type MyContractsReadParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the my contracts read params
func (o *MyContractsReadParams) WithTimeout(timeout time.Duration) *MyContractsReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the my contracts read params
func (o *MyContractsReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the my contracts read params
func (o *MyContractsReadParams) WithContext(ctx context.Context) *MyContractsReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the my contracts read params
func (o *MyContractsReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the my contracts read params
func (o *MyContractsReadParams) WithHTTPClient(client *http.Client) *MyContractsReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the my contracts read params
func (o *MyContractsReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the my contracts read params
func (o *MyContractsReadParams) WithID(id string) *MyContractsReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the my contracts read params
func (o *MyContractsReadParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *MyContractsReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
