// Code generated by go-swagger; DO NOT EDIT.

package my_contracts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// MyContractsCreateReader is a Reader for the MyContractsCreate structure.
type MyContractsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MyContractsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewMyContractsCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewMyContractsCreateCreated creates a MyContractsCreateCreated with default headers values
func NewMyContractsCreateCreated() *MyContractsCreateCreated {
	return &MyContractsCreateCreated{}
}

/*MyContractsCreateCreated handles this case with default header values.

MyContractsCreateCreated my contracts create created
*/
type MyContractsCreateCreated struct {
}

func (o *MyContractsCreateCreated) Error() string {
	return fmt.Sprintf("[POST /api/v1/my_contracts/][%d] myContractsCreateCreated ", 201)
}

func (o *MyContractsCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*MyContractsCreateBody my contracts create body
swagger:model MyContractsCreateBody
*/

type MyContractsCreateBody struct {

	// active
	Active bool `json:"active,omitempty"`

	// attachments
	Attachments []string `json:"attachments"`

	// company
	// Required: true
	Company *string `json:"company"`

	// contract groups
	ContractGroups []string `json:"contract_groups"`

	// customer
	// Required: true
	Customer *string `json:"customer"`

	// description
	Description string `json:"description,omitempty"`

	// label
	// Required: true
	Label *string `json:"label"`

	// performance types
	PerformanceTypes []string `json:"performance_types"`
}

/* polymorph MyContractsCreateBody active false */

/* polymorph MyContractsCreateBody attachments false */

/* polymorph MyContractsCreateBody company false */

/* polymorph MyContractsCreateBody contract_groups false */

/* polymorph MyContractsCreateBody customer false */

/* polymorph MyContractsCreateBody description false */

/* polymorph MyContractsCreateBody label false */

/* polymorph MyContractsCreateBody performance_types false */

// MarshalBinary interface implementation
func (o *MyContractsCreateBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *MyContractsCreateBody) UnmarshalBinary(b []byte) error {
	var res MyContractsCreateBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
