// Code generated by go-swagger; DO NOT EDIT.

package my_contracts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// MyContractsPartialUpdateReader is a Reader for the MyContractsPartialUpdate structure.
type MyContractsPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MyContractsPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewMyContractsPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewMyContractsPartialUpdateOK creates a MyContractsPartialUpdateOK with default headers values
func NewMyContractsPartialUpdateOK() *MyContractsPartialUpdateOK {
	return &MyContractsPartialUpdateOK{}
}

/*MyContractsPartialUpdateOK handles this case with default header values.

MyContractsPartialUpdateOK my contracts partial update o k
*/
type MyContractsPartialUpdateOK struct {
}

func (o *MyContractsPartialUpdateOK) Error() string {
	return fmt.Sprintf("[PATCH /api/v1/my_contracts/{id}/][%d] myContractsPartialUpdateOK ", 200)
}

func (o *MyContractsPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*MyContractsPartialUpdateBody my contracts partial update body
swagger:model MyContractsPartialUpdateBody
*/

type MyContractsPartialUpdateBody struct {

	// active
	Active bool `json:"active,omitempty"`

	// attachments
	Attachments []string `json:"attachments"`

	// company
	Company string `json:"company,omitempty"`

	// contract groups
	ContractGroups []string `json:"contract_groups"`

	// customer
	Customer string `json:"customer,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// label
	Label string `json:"label,omitempty"`

	// performance types
	PerformanceTypes []string `json:"performance_types"`
}

/* polymorph MyContractsPartialUpdateBody active false */

/* polymorph MyContractsPartialUpdateBody attachments false */

/* polymorph MyContractsPartialUpdateBody company false */

/* polymorph MyContractsPartialUpdateBody contract_groups false */

/* polymorph MyContractsPartialUpdateBody customer false */

/* polymorph MyContractsPartialUpdateBody description false */

/* polymorph MyContractsPartialUpdateBody label false */

/* polymorph MyContractsPartialUpdateBody performance_types false */

// MarshalBinary interface implementation
func (o *MyContractsPartialUpdateBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *MyContractsPartialUpdateBody) UnmarshalBinary(b []byte) error {
	var res MyContractsPartialUpdateBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
