// Code generated by go-swagger; DO NOT EDIT.

package my_contracts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// MyContractsUpdateReader is a Reader for the MyContractsUpdate structure.
type MyContractsUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MyContractsUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewMyContractsUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewMyContractsUpdateOK creates a MyContractsUpdateOK with default headers values
func NewMyContractsUpdateOK() *MyContractsUpdateOK {
	return &MyContractsUpdateOK{}
}

/*MyContractsUpdateOK handles this case with default header values.

MyContractsUpdateOK my contracts update o k
*/
type MyContractsUpdateOK struct {
}

func (o *MyContractsUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /api/v1/my_contracts/{id}/][%d] myContractsUpdateOK ", 200)
}

func (o *MyContractsUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*MyContractsUpdateBody my contracts update body
swagger:model MyContractsUpdateBody
*/

type MyContractsUpdateBody struct {

	// active
	Active bool `json:"active,omitempty"`

	// attachments
	Attachments []string `json:"attachments"`

	// company
	// Required: true
	Company *string `json:"company"`

	// contract groups
	ContractGroups []string `json:"contract_groups"`

	// customer
	// Required: true
	Customer *string `json:"customer"`

	// description
	Description string `json:"description,omitempty"`

	// label
	// Required: true
	Label *string `json:"label"`

	// performance types
	PerformanceTypes []string `json:"performance_types"`
}

/* polymorph MyContractsUpdateBody active false */

/* polymorph MyContractsUpdateBody attachments false */

/* polymorph MyContractsUpdateBody company false */

/* polymorph MyContractsUpdateBody contract_groups false */

/* polymorph MyContractsUpdateBody customer false */

/* polymorph MyContractsUpdateBody description false */

/* polymorph MyContractsUpdateBody label false */

/* polymorph MyContractsUpdateBody performance_types false */

// MarshalBinary interface implementation
func (o *MyContractsUpdateBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *MyContractsUpdateBody) UnmarshalBinary(b []byte) error {
	var res MyContractsUpdateBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
