// Code generated by go-swagger; DO NOT EDIT.

package my_contracts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewMyContractsPartialUpdateParams creates a new MyContractsPartialUpdateParams object
// with the default values initialized.
func NewMyContractsPartialUpdateParams() *MyContractsPartialUpdateParams {
	var ()
	return &MyContractsPartialUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMyContractsPartialUpdateParamsWithTimeout creates a new MyContractsPartialUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMyContractsPartialUpdateParamsWithTimeout(timeout time.Duration) *MyContractsPartialUpdateParams {
	var ()
	return &MyContractsPartialUpdateParams{

		timeout: timeout,
	}
}

// NewMyContractsPartialUpdateParamsWithContext creates a new MyContractsPartialUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewMyContractsPartialUpdateParamsWithContext(ctx context.Context) *MyContractsPartialUpdateParams {
	var ()
	return &MyContractsPartialUpdateParams{

		Context: ctx,
	}
}

// NewMyContractsPartialUpdateParamsWithHTTPClient creates a new MyContractsPartialUpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMyContractsPartialUpdateParamsWithHTTPClient(client *http.Client) *MyContractsPartialUpdateParams {
	var ()
	return &MyContractsPartialUpdateParams{
		HTTPClient: client,
	}
}

/*MyContractsPartialUpdateParams contains all the parameters to send to the API endpoint
for the my contracts partial update operation typically these are written to a http.Request
*/
type MyContractsPartialUpdateParams struct {

	/*Data*/
	Data MyContractsPartialUpdateBody
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the my contracts partial update params
func (o *MyContractsPartialUpdateParams) WithTimeout(timeout time.Duration) *MyContractsPartialUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the my contracts partial update params
func (o *MyContractsPartialUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the my contracts partial update params
func (o *MyContractsPartialUpdateParams) WithContext(ctx context.Context) *MyContractsPartialUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the my contracts partial update params
func (o *MyContractsPartialUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the my contracts partial update params
func (o *MyContractsPartialUpdateParams) WithHTTPClient(client *http.Client) *MyContractsPartialUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the my contracts partial update params
func (o *MyContractsPartialUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the my contracts partial update params
func (o *MyContractsPartialUpdateParams) WithData(data MyContractsPartialUpdateBody) *MyContractsPartialUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the my contracts partial update params
func (o *MyContractsPartialUpdateParams) SetData(data MyContractsPartialUpdateBody) {
	o.Data = data
}

// WithID adds the id to the my contracts partial update params
func (o *MyContractsPartialUpdateParams) WithID(id string) *MyContractsPartialUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the my contracts partial update params
func (o *MyContractsPartialUpdateParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *MyContractsPartialUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
