// Code generated by go-swagger; DO NOT EDIT.

package my_contracts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewMyContractsListParams creates a new MyContractsListParams object
// with the default values initialized.
func NewMyContractsListParams() *MyContractsListParams {
	var ()
	return &MyContractsListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMyContractsListParamsWithTimeout creates a new MyContractsListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMyContractsListParamsWithTimeout(timeout time.Duration) *MyContractsListParams {
	var ()
	return &MyContractsListParams{

		timeout: timeout,
	}
}

// NewMyContractsListParamsWithContext creates a new MyContractsListParams object
// with the default values initialized, and the ability to set a context for a request
func NewMyContractsListParamsWithContext(ctx context.Context) *MyContractsListParams {
	var ()
	return &MyContractsListParams{

		Context: ctx,
	}
}

// NewMyContractsListParamsWithHTTPClient creates a new MyContractsListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMyContractsListParamsWithHTTPClient(client *http.Client) *MyContractsListParams {
	var ()
	return &MyContractsListParams{
		HTTPClient: client,
	}
}

/*MyContractsListParams contains all the parameters to send to the API endpoint
for the my contracts list operation typically these are written to a http.Request
*/
type MyContractsListParams struct {

	/*Active*/
	Active *string
	/*Company*/
	Company *string
	/*CompanyCountry*/
	CompanyCountry *string
	/*CompanyInternal*/
	CompanyInternal *string
	/*CompanyName*/
	CompanyName *string
	/*CompanyNameContains*/
	CompanyNameContains *string
	/*CompanyNameIcontains*/
	CompanyNameIcontains *string
	/*CompanyVatIdentificationNumber*/
	CompanyVatIdentificationNumber *string
	/*ContractGroupsLabel*/
	ContractGroupsLabel *string
	/*ContractGroupsLabelContains*/
	ContractGroupsLabelContains *string
	/*ContractGroupsLabelIcontains*/
	ContractGroupsLabelIcontains *string
	/*ContractuserUserFirstName*/
	ContractuserUserFirstName *string
	/*ContractuserUserFirstNameContains*/
	ContractuserUserFirstNameContains *string
	/*ContractuserUserFirstNameIcontains*/
	ContractuserUserFirstNameIcontains *string
	/*ContractuserUserGroups*/
	ContractuserUserGroups *string
	/*ContractuserUserGroupsContains*/
	ContractuserUserGroupsContains *string
	/*ContractuserUserGroupsIcontains*/
	ContractuserUserGroupsIcontains *string
	/*ContractuserUserID*/
	ContractuserUserID *string
	/*ContractuserUserLastName*/
	ContractuserUserLastName *string
	/*ContractuserUserLastNameContains*/
	ContractuserUserLastNameContains *string
	/*ContractuserUserLastNameIcontains*/
	ContractuserUserLastNameIcontains *string
	/*ContractuserUserUsername*/
	ContractuserUserUsername *string
	/*ContractuserUserUsernameContains*/
	ContractuserUserUsernameContains *string
	/*ContractuserUserUsernameIcontains*/
	ContractuserUserUsernameIcontains *string
	/*CustomerCountry*/
	CustomerCountry *string
	/*CustomerInternal*/
	CustomerInternal *string
	/*CustomerName*/
	CustomerName *string
	/*CustomerNameContains*/
	CustomerNameContains *string
	/*CustomerNameIcontains*/
	CustomerNameIcontains *string
	/*CustomerVatIdentificationNumber*/
	CustomerVatIdentificationNumber *string
	/*Description*/
	Description *string
	/*DescriptionContains*/
	DescriptionContains *string
	/*DescriptionIcontains*/
	DescriptionIcontains *string
	/*Label*/
	Label *string
	/*LabelContains*/
	LabelContains *string
	/*LabelIcontains*/
	LabelIcontains *string
	/*OrderBy*/
	OrderBy *string
	/*Page*/
	Page *string
	/*PageSize*/
	PageSize *string
	/*PerformanceTypesID*/
	PerformanceTypesID *string
	/*PerformanceTypesLabel*/
	PerformanceTypesLabel *string
	/*PerformanceTypesLabelContains*/
	PerformanceTypesLabelContains *string
	/*PerformanceTypesLabelIcontains*/
	PerformanceTypesLabelIcontains *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the my contracts list params
func (o *MyContractsListParams) WithTimeout(timeout time.Duration) *MyContractsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the my contracts list params
func (o *MyContractsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the my contracts list params
func (o *MyContractsListParams) WithContext(ctx context.Context) *MyContractsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the my contracts list params
func (o *MyContractsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the my contracts list params
func (o *MyContractsListParams) WithHTTPClient(client *http.Client) *MyContractsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the my contracts list params
func (o *MyContractsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithActive adds the active to the my contracts list params
func (o *MyContractsListParams) WithActive(active *string) *MyContractsListParams {
	o.SetActive(active)
	return o
}

// SetActive adds the active to the my contracts list params
func (o *MyContractsListParams) SetActive(active *string) {
	o.Active = active
}

// WithCompany adds the company to the my contracts list params
func (o *MyContractsListParams) WithCompany(company *string) *MyContractsListParams {
	o.SetCompany(company)
	return o
}

// SetCompany adds the company to the my contracts list params
func (o *MyContractsListParams) SetCompany(company *string) {
	o.Company = company
}

// WithCompanyCountry adds the companyCountry to the my contracts list params
func (o *MyContractsListParams) WithCompanyCountry(companyCountry *string) *MyContractsListParams {
	o.SetCompanyCountry(companyCountry)
	return o
}

// SetCompanyCountry adds the companyCountry to the my contracts list params
func (o *MyContractsListParams) SetCompanyCountry(companyCountry *string) {
	o.CompanyCountry = companyCountry
}

// WithCompanyInternal adds the companyInternal to the my contracts list params
func (o *MyContractsListParams) WithCompanyInternal(companyInternal *string) *MyContractsListParams {
	o.SetCompanyInternal(companyInternal)
	return o
}

// SetCompanyInternal adds the companyInternal to the my contracts list params
func (o *MyContractsListParams) SetCompanyInternal(companyInternal *string) {
	o.CompanyInternal = companyInternal
}

// WithCompanyName adds the companyName to the my contracts list params
func (o *MyContractsListParams) WithCompanyName(companyName *string) *MyContractsListParams {
	o.SetCompanyName(companyName)
	return o
}

// SetCompanyName adds the companyName to the my contracts list params
func (o *MyContractsListParams) SetCompanyName(companyName *string) {
	o.CompanyName = companyName
}

// WithCompanyNameContains adds the companyNameContains to the my contracts list params
func (o *MyContractsListParams) WithCompanyNameContains(companyNameContains *string) *MyContractsListParams {
	o.SetCompanyNameContains(companyNameContains)
	return o
}

// SetCompanyNameContains adds the companyNameContains to the my contracts list params
func (o *MyContractsListParams) SetCompanyNameContains(companyNameContains *string) {
	o.CompanyNameContains = companyNameContains
}

// WithCompanyNameIcontains adds the companyNameIcontains to the my contracts list params
func (o *MyContractsListParams) WithCompanyNameIcontains(companyNameIcontains *string) *MyContractsListParams {
	o.SetCompanyNameIcontains(companyNameIcontains)
	return o
}

// SetCompanyNameIcontains adds the companyNameIcontains to the my contracts list params
func (o *MyContractsListParams) SetCompanyNameIcontains(companyNameIcontains *string) {
	o.CompanyNameIcontains = companyNameIcontains
}

// WithCompanyVatIdentificationNumber adds the companyVatIdentificationNumber to the my contracts list params
func (o *MyContractsListParams) WithCompanyVatIdentificationNumber(companyVatIdentificationNumber *string) *MyContractsListParams {
	o.SetCompanyVatIdentificationNumber(companyVatIdentificationNumber)
	return o
}

// SetCompanyVatIdentificationNumber adds the companyVatIdentificationNumber to the my contracts list params
func (o *MyContractsListParams) SetCompanyVatIdentificationNumber(companyVatIdentificationNumber *string) {
	o.CompanyVatIdentificationNumber = companyVatIdentificationNumber
}

// WithContractGroupsLabel adds the contractGroupsLabel to the my contracts list params
func (o *MyContractsListParams) WithContractGroupsLabel(contractGroupsLabel *string) *MyContractsListParams {
	o.SetContractGroupsLabel(contractGroupsLabel)
	return o
}

// SetContractGroupsLabel adds the contractGroupsLabel to the my contracts list params
func (o *MyContractsListParams) SetContractGroupsLabel(contractGroupsLabel *string) {
	o.ContractGroupsLabel = contractGroupsLabel
}

// WithContractGroupsLabelContains adds the contractGroupsLabelContains to the my contracts list params
func (o *MyContractsListParams) WithContractGroupsLabelContains(contractGroupsLabelContains *string) *MyContractsListParams {
	o.SetContractGroupsLabelContains(contractGroupsLabelContains)
	return o
}

// SetContractGroupsLabelContains adds the contractGroupsLabelContains to the my contracts list params
func (o *MyContractsListParams) SetContractGroupsLabelContains(contractGroupsLabelContains *string) {
	o.ContractGroupsLabelContains = contractGroupsLabelContains
}

// WithContractGroupsLabelIcontains adds the contractGroupsLabelIcontains to the my contracts list params
func (o *MyContractsListParams) WithContractGroupsLabelIcontains(contractGroupsLabelIcontains *string) *MyContractsListParams {
	o.SetContractGroupsLabelIcontains(contractGroupsLabelIcontains)
	return o
}

// SetContractGroupsLabelIcontains adds the contractGroupsLabelIcontains to the my contracts list params
func (o *MyContractsListParams) SetContractGroupsLabelIcontains(contractGroupsLabelIcontains *string) {
	o.ContractGroupsLabelIcontains = contractGroupsLabelIcontains
}

// WithContractuserUserFirstName adds the contractuserUserFirstName to the my contracts list params
func (o *MyContractsListParams) WithContractuserUserFirstName(contractuserUserFirstName *string) *MyContractsListParams {
	o.SetContractuserUserFirstName(contractuserUserFirstName)
	return o
}

// SetContractuserUserFirstName adds the contractuserUserFirstName to the my contracts list params
func (o *MyContractsListParams) SetContractuserUserFirstName(contractuserUserFirstName *string) {
	o.ContractuserUserFirstName = contractuserUserFirstName
}

// WithContractuserUserFirstNameContains adds the contractuserUserFirstNameContains to the my contracts list params
func (o *MyContractsListParams) WithContractuserUserFirstNameContains(contractuserUserFirstNameContains *string) *MyContractsListParams {
	o.SetContractuserUserFirstNameContains(contractuserUserFirstNameContains)
	return o
}

// SetContractuserUserFirstNameContains adds the contractuserUserFirstNameContains to the my contracts list params
func (o *MyContractsListParams) SetContractuserUserFirstNameContains(contractuserUserFirstNameContains *string) {
	o.ContractuserUserFirstNameContains = contractuserUserFirstNameContains
}

// WithContractuserUserFirstNameIcontains adds the contractuserUserFirstNameIcontains to the my contracts list params
func (o *MyContractsListParams) WithContractuserUserFirstNameIcontains(contractuserUserFirstNameIcontains *string) *MyContractsListParams {
	o.SetContractuserUserFirstNameIcontains(contractuserUserFirstNameIcontains)
	return o
}

// SetContractuserUserFirstNameIcontains adds the contractuserUserFirstNameIcontains to the my contracts list params
func (o *MyContractsListParams) SetContractuserUserFirstNameIcontains(contractuserUserFirstNameIcontains *string) {
	o.ContractuserUserFirstNameIcontains = contractuserUserFirstNameIcontains
}

// WithContractuserUserGroups adds the contractuserUserGroups to the my contracts list params
func (o *MyContractsListParams) WithContractuserUserGroups(contractuserUserGroups *string) *MyContractsListParams {
	o.SetContractuserUserGroups(contractuserUserGroups)
	return o
}

// SetContractuserUserGroups adds the contractuserUserGroups to the my contracts list params
func (o *MyContractsListParams) SetContractuserUserGroups(contractuserUserGroups *string) {
	o.ContractuserUserGroups = contractuserUserGroups
}

// WithContractuserUserGroupsContains adds the contractuserUserGroupsContains to the my contracts list params
func (o *MyContractsListParams) WithContractuserUserGroupsContains(contractuserUserGroupsContains *string) *MyContractsListParams {
	o.SetContractuserUserGroupsContains(contractuserUserGroupsContains)
	return o
}

// SetContractuserUserGroupsContains adds the contractuserUserGroupsContains to the my contracts list params
func (o *MyContractsListParams) SetContractuserUserGroupsContains(contractuserUserGroupsContains *string) {
	o.ContractuserUserGroupsContains = contractuserUserGroupsContains
}

// WithContractuserUserGroupsIcontains adds the contractuserUserGroupsIcontains to the my contracts list params
func (o *MyContractsListParams) WithContractuserUserGroupsIcontains(contractuserUserGroupsIcontains *string) *MyContractsListParams {
	o.SetContractuserUserGroupsIcontains(contractuserUserGroupsIcontains)
	return o
}

// SetContractuserUserGroupsIcontains adds the contractuserUserGroupsIcontains to the my contracts list params
func (o *MyContractsListParams) SetContractuserUserGroupsIcontains(contractuserUserGroupsIcontains *string) {
	o.ContractuserUserGroupsIcontains = contractuserUserGroupsIcontains
}

// WithContractuserUserID adds the contractuserUserID to the my contracts list params
func (o *MyContractsListParams) WithContractuserUserID(contractuserUserID *string) *MyContractsListParams {
	o.SetContractuserUserID(contractuserUserID)
	return o
}

// SetContractuserUserID adds the contractuserUserId to the my contracts list params
func (o *MyContractsListParams) SetContractuserUserID(contractuserUserID *string) {
	o.ContractuserUserID = contractuserUserID
}

// WithContractuserUserLastName adds the contractuserUserLastName to the my contracts list params
func (o *MyContractsListParams) WithContractuserUserLastName(contractuserUserLastName *string) *MyContractsListParams {
	o.SetContractuserUserLastName(contractuserUserLastName)
	return o
}

// SetContractuserUserLastName adds the contractuserUserLastName to the my contracts list params
func (o *MyContractsListParams) SetContractuserUserLastName(contractuserUserLastName *string) {
	o.ContractuserUserLastName = contractuserUserLastName
}

// WithContractuserUserLastNameContains adds the contractuserUserLastNameContains to the my contracts list params
func (o *MyContractsListParams) WithContractuserUserLastNameContains(contractuserUserLastNameContains *string) *MyContractsListParams {
	o.SetContractuserUserLastNameContains(contractuserUserLastNameContains)
	return o
}

// SetContractuserUserLastNameContains adds the contractuserUserLastNameContains to the my contracts list params
func (o *MyContractsListParams) SetContractuserUserLastNameContains(contractuserUserLastNameContains *string) {
	o.ContractuserUserLastNameContains = contractuserUserLastNameContains
}

// WithContractuserUserLastNameIcontains adds the contractuserUserLastNameIcontains to the my contracts list params
func (o *MyContractsListParams) WithContractuserUserLastNameIcontains(contractuserUserLastNameIcontains *string) *MyContractsListParams {
	o.SetContractuserUserLastNameIcontains(contractuserUserLastNameIcontains)
	return o
}

// SetContractuserUserLastNameIcontains adds the contractuserUserLastNameIcontains to the my contracts list params
func (o *MyContractsListParams) SetContractuserUserLastNameIcontains(contractuserUserLastNameIcontains *string) {
	o.ContractuserUserLastNameIcontains = contractuserUserLastNameIcontains
}

// WithContractuserUserUsername adds the contractuserUserUsername to the my contracts list params
func (o *MyContractsListParams) WithContractuserUserUsername(contractuserUserUsername *string) *MyContractsListParams {
	o.SetContractuserUserUsername(contractuserUserUsername)
	return o
}

// SetContractuserUserUsername adds the contractuserUserUsername to the my contracts list params
func (o *MyContractsListParams) SetContractuserUserUsername(contractuserUserUsername *string) {
	o.ContractuserUserUsername = contractuserUserUsername
}

// WithContractuserUserUsernameContains adds the contractuserUserUsernameContains to the my contracts list params
func (o *MyContractsListParams) WithContractuserUserUsernameContains(contractuserUserUsernameContains *string) *MyContractsListParams {
	o.SetContractuserUserUsernameContains(contractuserUserUsernameContains)
	return o
}

// SetContractuserUserUsernameContains adds the contractuserUserUsernameContains to the my contracts list params
func (o *MyContractsListParams) SetContractuserUserUsernameContains(contractuserUserUsernameContains *string) {
	o.ContractuserUserUsernameContains = contractuserUserUsernameContains
}

// WithContractuserUserUsernameIcontains adds the contractuserUserUsernameIcontains to the my contracts list params
func (o *MyContractsListParams) WithContractuserUserUsernameIcontains(contractuserUserUsernameIcontains *string) *MyContractsListParams {
	o.SetContractuserUserUsernameIcontains(contractuserUserUsernameIcontains)
	return o
}

// SetContractuserUserUsernameIcontains adds the contractuserUserUsernameIcontains to the my contracts list params
func (o *MyContractsListParams) SetContractuserUserUsernameIcontains(contractuserUserUsernameIcontains *string) {
	o.ContractuserUserUsernameIcontains = contractuserUserUsernameIcontains
}

// WithCustomerCountry adds the customerCountry to the my contracts list params
func (o *MyContractsListParams) WithCustomerCountry(customerCountry *string) *MyContractsListParams {
	o.SetCustomerCountry(customerCountry)
	return o
}

// SetCustomerCountry adds the customerCountry to the my contracts list params
func (o *MyContractsListParams) SetCustomerCountry(customerCountry *string) {
	o.CustomerCountry = customerCountry
}

// WithCustomerInternal adds the customerInternal to the my contracts list params
func (o *MyContractsListParams) WithCustomerInternal(customerInternal *string) *MyContractsListParams {
	o.SetCustomerInternal(customerInternal)
	return o
}

// SetCustomerInternal adds the customerInternal to the my contracts list params
func (o *MyContractsListParams) SetCustomerInternal(customerInternal *string) {
	o.CustomerInternal = customerInternal
}

// WithCustomerName adds the customerName to the my contracts list params
func (o *MyContractsListParams) WithCustomerName(customerName *string) *MyContractsListParams {
	o.SetCustomerName(customerName)
	return o
}

// SetCustomerName adds the customerName to the my contracts list params
func (o *MyContractsListParams) SetCustomerName(customerName *string) {
	o.CustomerName = customerName
}

// WithCustomerNameContains adds the customerNameContains to the my contracts list params
func (o *MyContractsListParams) WithCustomerNameContains(customerNameContains *string) *MyContractsListParams {
	o.SetCustomerNameContains(customerNameContains)
	return o
}

// SetCustomerNameContains adds the customerNameContains to the my contracts list params
func (o *MyContractsListParams) SetCustomerNameContains(customerNameContains *string) {
	o.CustomerNameContains = customerNameContains
}

// WithCustomerNameIcontains adds the customerNameIcontains to the my contracts list params
func (o *MyContractsListParams) WithCustomerNameIcontains(customerNameIcontains *string) *MyContractsListParams {
	o.SetCustomerNameIcontains(customerNameIcontains)
	return o
}

// SetCustomerNameIcontains adds the customerNameIcontains to the my contracts list params
func (o *MyContractsListParams) SetCustomerNameIcontains(customerNameIcontains *string) {
	o.CustomerNameIcontains = customerNameIcontains
}

// WithCustomerVatIdentificationNumber adds the customerVatIdentificationNumber to the my contracts list params
func (o *MyContractsListParams) WithCustomerVatIdentificationNumber(customerVatIdentificationNumber *string) *MyContractsListParams {
	o.SetCustomerVatIdentificationNumber(customerVatIdentificationNumber)
	return o
}

// SetCustomerVatIdentificationNumber adds the customerVatIdentificationNumber to the my contracts list params
func (o *MyContractsListParams) SetCustomerVatIdentificationNumber(customerVatIdentificationNumber *string) {
	o.CustomerVatIdentificationNumber = customerVatIdentificationNumber
}

// WithDescription adds the description to the my contracts list params
func (o *MyContractsListParams) WithDescription(description *string) *MyContractsListParams {
	o.SetDescription(description)
	return o
}

// SetDescription adds the description to the my contracts list params
func (o *MyContractsListParams) SetDescription(description *string) {
	o.Description = description
}

// WithDescriptionContains adds the descriptionContains to the my contracts list params
func (o *MyContractsListParams) WithDescriptionContains(descriptionContains *string) *MyContractsListParams {
	o.SetDescriptionContains(descriptionContains)
	return o
}

// SetDescriptionContains adds the descriptionContains to the my contracts list params
func (o *MyContractsListParams) SetDescriptionContains(descriptionContains *string) {
	o.DescriptionContains = descriptionContains
}

// WithDescriptionIcontains adds the descriptionIcontains to the my contracts list params
func (o *MyContractsListParams) WithDescriptionIcontains(descriptionIcontains *string) *MyContractsListParams {
	o.SetDescriptionIcontains(descriptionIcontains)
	return o
}

// SetDescriptionIcontains adds the descriptionIcontains to the my contracts list params
func (o *MyContractsListParams) SetDescriptionIcontains(descriptionIcontains *string) {
	o.DescriptionIcontains = descriptionIcontains
}

// WithLabel adds the label to the my contracts list params
func (o *MyContractsListParams) WithLabel(label *string) *MyContractsListParams {
	o.SetLabel(label)
	return o
}

// SetLabel adds the label to the my contracts list params
func (o *MyContractsListParams) SetLabel(label *string) {
	o.Label = label
}

// WithLabelContains adds the labelContains to the my contracts list params
func (o *MyContractsListParams) WithLabelContains(labelContains *string) *MyContractsListParams {
	o.SetLabelContains(labelContains)
	return o
}

// SetLabelContains adds the labelContains to the my contracts list params
func (o *MyContractsListParams) SetLabelContains(labelContains *string) {
	o.LabelContains = labelContains
}

// WithLabelIcontains adds the labelIcontains to the my contracts list params
func (o *MyContractsListParams) WithLabelIcontains(labelIcontains *string) *MyContractsListParams {
	o.SetLabelIcontains(labelIcontains)
	return o
}

// SetLabelIcontains adds the labelIcontains to the my contracts list params
func (o *MyContractsListParams) SetLabelIcontains(labelIcontains *string) {
	o.LabelIcontains = labelIcontains
}

// WithOrderBy adds the orderBy to the my contracts list params
func (o *MyContractsListParams) WithOrderBy(orderBy *string) *MyContractsListParams {
	o.SetOrderBy(orderBy)
	return o
}

// SetOrderBy adds the orderBy to the my contracts list params
func (o *MyContractsListParams) SetOrderBy(orderBy *string) {
	o.OrderBy = orderBy
}

// WithPage adds the page to the my contracts list params
func (o *MyContractsListParams) WithPage(page *string) *MyContractsListParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the my contracts list params
func (o *MyContractsListParams) SetPage(page *string) {
	o.Page = page
}

// WithPageSize adds the pageSize to the my contracts list params
func (o *MyContractsListParams) WithPageSize(pageSize *string) *MyContractsListParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the my contracts list params
func (o *MyContractsListParams) SetPageSize(pageSize *string) {
	o.PageSize = pageSize
}

// WithPerformanceTypesID adds the performanceTypesID to the my contracts list params
func (o *MyContractsListParams) WithPerformanceTypesID(performanceTypesID *string) *MyContractsListParams {
	o.SetPerformanceTypesID(performanceTypesID)
	return o
}

// SetPerformanceTypesID adds the performanceTypesId to the my contracts list params
func (o *MyContractsListParams) SetPerformanceTypesID(performanceTypesID *string) {
	o.PerformanceTypesID = performanceTypesID
}

// WithPerformanceTypesLabel adds the performanceTypesLabel to the my contracts list params
func (o *MyContractsListParams) WithPerformanceTypesLabel(performanceTypesLabel *string) *MyContractsListParams {
	o.SetPerformanceTypesLabel(performanceTypesLabel)
	return o
}

// SetPerformanceTypesLabel adds the performanceTypesLabel to the my contracts list params
func (o *MyContractsListParams) SetPerformanceTypesLabel(performanceTypesLabel *string) {
	o.PerformanceTypesLabel = performanceTypesLabel
}

// WithPerformanceTypesLabelContains adds the performanceTypesLabelContains to the my contracts list params
func (o *MyContractsListParams) WithPerformanceTypesLabelContains(performanceTypesLabelContains *string) *MyContractsListParams {
	o.SetPerformanceTypesLabelContains(performanceTypesLabelContains)
	return o
}

// SetPerformanceTypesLabelContains adds the performanceTypesLabelContains to the my contracts list params
func (o *MyContractsListParams) SetPerformanceTypesLabelContains(performanceTypesLabelContains *string) {
	o.PerformanceTypesLabelContains = performanceTypesLabelContains
}

// WithPerformanceTypesLabelIcontains adds the performanceTypesLabelIcontains to the my contracts list params
func (o *MyContractsListParams) WithPerformanceTypesLabelIcontains(performanceTypesLabelIcontains *string) *MyContractsListParams {
	o.SetPerformanceTypesLabelIcontains(performanceTypesLabelIcontains)
	return o
}

// SetPerformanceTypesLabelIcontains adds the performanceTypesLabelIcontains to the my contracts list params
func (o *MyContractsListParams) SetPerformanceTypesLabelIcontains(performanceTypesLabelIcontains *string) {
	o.PerformanceTypesLabelIcontains = performanceTypesLabelIcontains
}

// WriteToRequest writes these params to a swagger request
func (o *MyContractsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Active != nil {

		// query param active
		var qrActive string
		if o.Active != nil {
			qrActive = *o.Active
		}
		qActive := qrActive
		if qActive != "" {
			if err := r.SetQueryParam("active", qActive); err != nil {
				return err
			}
		}

	}

	if o.Company != nil {

		// query param company
		var qrCompany string
		if o.Company != nil {
			qrCompany = *o.Company
		}
		qCompany := qrCompany
		if qCompany != "" {
			if err := r.SetQueryParam("company", qCompany); err != nil {
				return err
			}
		}

	}

	if o.CompanyCountry != nil {

		// query param company__country
		var qrCompanyCountry string
		if o.CompanyCountry != nil {
			qrCompanyCountry = *o.CompanyCountry
		}
		qCompanyCountry := qrCompanyCountry
		if qCompanyCountry != "" {
			if err := r.SetQueryParam("company__country", qCompanyCountry); err != nil {
				return err
			}
		}

	}

	if o.CompanyInternal != nil {

		// query param company__internal
		var qrCompanyInternal string
		if o.CompanyInternal != nil {
			qrCompanyInternal = *o.CompanyInternal
		}
		qCompanyInternal := qrCompanyInternal
		if qCompanyInternal != "" {
			if err := r.SetQueryParam("company__internal", qCompanyInternal); err != nil {
				return err
			}
		}

	}

	if o.CompanyName != nil {

		// query param company__name
		var qrCompanyName string
		if o.CompanyName != nil {
			qrCompanyName = *o.CompanyName
		}
		qCompanyName := qrCompanyName
		if qCompanyName != "" {
			if err := r.SetQueryParam("company__name", qCompanyName); err != nil {
				return err
			}
		}

	}

	if o.CompanyNameContains != nil {

		// query param company__name__contains
		var qrCompanyNameContains string
		if o.CompanyNameContains != nil {
			qrCompanyNameContains = *o.CompanyNameContains
		}
		qCompanyNameContains := qrCompanyNameContains
		if qCompanyNameContains != "" {
			if err := r.SetQueryParam("company__name__contains", qCompanyNameContains); err != nil {
				return err
			}
		}

	}

	if o.CompanyNameIcontains != nil {

		// query param company__name__icontains
		var qrCompanyNameIcontains string
		if o.CompanyNameIcontains != nil {
			qrCompanyNameIcontains = *o.CompanyNameIcontains
		}
		qCompanyNameIcontains := qrCompanyNameIcontains
		if qCompanyNameIcontains != "" {
			if err := r.SetQueryParam("company__name__icontains", qCompanyNameIcontains); err != nil {
				return err
			}
		}

	}

	if o.CompanyVatIdentificationNumber != nil {

		// query param company__vat_identification_number
		var qrCompanyVatIdentificationNumber string
		if o.CompanyVatIdentificationNumber != nil {
			qrCompanyVatIdentificationNumber = *o.CompanyVatIdentificationNumber
		}
		qCompanyVatIdentificationNumber := qrCompanyVatIdentificationNumber
		if qCompanyVatIdentificationNumber != "" {
			if err := r.SetQueryParam("company__vat_identification_number", qCompanyVatIdentificationNumber); err != nil {
				return err
			}
		}

	}

	if o.ContractGroupsLabel != nil {

		// query param contract_groups__label
		var qrContractGroupsLabel string
		if o.ContractGroupsLabel != nil {
			qrContractGroupsLabel = *o.ContractGroupsLabel
		}
		qContractGroupsLabel := qrContractGroupsLabel
		if qContractGroupsLabel != "" {
			if err := r.SetQueryParam("contract_groups__label", qContractGroupsLabel); err != nil {
				return err
			}
		}

	}

	if o.ContractGroupsLabelContains != nil {

		// query param contract_groups__label__contains
		var qrContractGroupsLabelContains string
		if o.ContractGroupsLabelContains != nil {
			qrContractGroupsLabelContains = *o.ContractGroupsLabelContains
		}
		qContractGroupsLabelContains := qrContractGroupsLabelContains
		if qContractGroupsLabelContains != "" {
			if err := r.SetQueryParam("contract_groups__label__contains", qContractGroupsLabelContains); err != nil {
				return err
			}
		}

	}

	if o.ContractGroupsLabelIcontains != nil {

		// query param contract_groups__label__icontains
		var qrContractGroupsLabelIcontains string
		if o.ContractGroupsLabelIcontains != nil {
			qrContractGroupsLabelIcontains = *o.ContractGroupsLabelIcontains
		}
		qContractGroupsLabelIcontains := qrContractGroupsLabelIcontains
		if qContractGroupsLabelIcontains != "" {
			if err := r.SetQueryParam("contract_groups__label__icontains", qContractGroupsLabelIcontains); err != nil {
				return err
			}
		}

	}

	if o.ContractuserUserFirstName != nil {

		// query param contractuser__user__first_name
		var qrContractuserUserFirstName string
		if o.ContractuserUserFirstName != nil {
			qrContractuserUserFirstName = *o.ContractuserUserFirstName
		}
		qContractuserUserFirstName := qrContractuserUserFirstName
		if qContractuserUserFirstName != "" {
			if err := r.SetQueryParam("contractuser__user__first_name", qContractuserUserFirstName); err != nil {
				return err
			}
		}

	}

	if o.ContractuserUserFirstNameContains != nil {

		// query param contractuser__user__first_name__contains
		var qrContractuserUserFirstNameContains string
		if o.ContractuserUserFirstNameContains != nil {
			qrContractuserUserFirstNameContains = *o.ContractuserUserFirstNameContains
		}
		qContractuserUserFirstNameContains := qrContractuserUserFirstNameContains
		if qContractuserUserFirstNameContains != "" {
			if err := r.SetQueryParam("contractuser__user__first_name__contains", qContractuserUserFirstNameContains); err != nil {
				return err
			}
		}

	}

	if o.ContractuserUserFirstNameIcontains != nil {

		// query param contractuser__user__first_name__icontains
		var qrContractuserUserFirstNameIcontains string
		if o.ContractuserUserFirstNameIcontains != nil {
			qrContractuserUserFirstNameIcontains = *o.ContractuserUserFirstNameIcontains
		}
		qContractuserUserFirstNameIcontains := qrContractuserUserFirstNameIcontains
		if qContractuserUserFirstNameIcontains != "" {
			if err := r.SetQueryParam("contractuser__user__first_name__icontains", qContractuserUserFirstNameIcontains); err != nil {
				return err
			}
		}

	}

	if o.ContractuserUserGroups != nil {

		// query param contractuser__user__groups
		var qrContractuserUserGroups string
		if o.ContractuserUserGroups != nil {
			qrContractuserUserGroups = *o.ContractuserUserGroups
		}
		qContractuserUserGroups := qrContractuserUserGroups
		if qContractuserUserGroups != "" {
			if err := r.SetQueryParam("contractuser__user__groups", qContractuserUserGroups); err != nil {
				return err
			}
		}

	}

	if o.ContractuserUserGroupsContains != nil {

		// query param contractuser__user__groups__contains
		var qrContractuserUserGroupsContains string
		if o.ContractuserUserGroupsContains != nil {
			qrContractuserUserGroupsContains = *o.ContractuserUserGroupsContains
		}
		qContractuserUserGroupsContains := qrContractuserUserGroupsContains
		if qContractuserUserGroupsContains != "" {
			if err := r.SetQueryParam("contractuser__user__groups__contains", qContractuserUserGroupsContains); err != nil {
				return err
			}
		}

	}

	if o.ContractuserUserGroupsIcontains != nil {

		// query param contractuser__user__groups__icontains
		var qrContractuserUserGroupsIcontains string
		if o.ContractuserUserGroupsIcontains != nil {
			qrContractuserUserGroupsIcontains = *o.ContractuserUserGroupsIcontains
		}
		qContractuserUserGroupsIcontains := qrContractuserUserGroupsIcontains
		if qContractuserUserGroupsIcontains != "" {
			if err := r.SetQueryParam("contractuser__user__groups__icontains", qContractuserUserGroupsIcontains); err != nil {
				return err
			}
		}

	}

	if o.ContractuserUserID != nil {

		// query param contractuser__user__id
		var qrContractuserUserID string
		if o.ContractuserUserID != nil {
			qrContractuserUserID = *o.ContractuserUserID
		}
		qContractuserUserID := qrContractuserUserID
		if qContractuserUserID != "" {
			if err := r.SetQueryParam("contractuser__user__id", qContractuserUserID); err != nil {
				return err
			}
		}

	}

	if o.ContractuserUserLastName != nil {

		// query param contractuser__user__last_name
		var qrContractuserUserLastName string
		if o.ContractuserUserLastName != nil {
			qrContractuserUserLastName = *o.ContractuserUserLastName
		}
		qContractuserUserLastName := qrContractuserUserLastName
		if qContractuserUserLastName != "" {
			if err := r.SetQueryParam("contractuser__user__last_name", qContractuserUserLastName); err != nil {
				return err
			}
		}

	}

	if o.ContractuserUserLastNameContains != nil {

		// query param contractuser__user__last_name__contains
		var qrContractuserUserLastNameContains string
		if o.ContractuserUserLastNameContains != nil {
			qrContractuserUserLastNameContains = *o.ContractuserUserLastNameContains
		}
		qContractuserUserLastNameContains := qrContractuserUserLastNameContains
		if qContractuserUserLastNameContains != "" {
			if err := r.SetQueryParam("contractuser__user__last_name__contains", qContractuserUserLastNameContains); err != nil {
				return err
			}
		}

	}

	if o.ContractuserUserLastNameIcontains != nil {

		// query param contractuser__user__last_name__icontains
		var qrContractuserUserLastNameIcontains string
		if o.ContractuserUserLastNameIcontains != nil {
			qrContractuserUserLastNameIcontains = *o.ContractuserUserLastNameIcontains
		}
		qContractuserUserLastNameIcontains := qrContractuserUserLastNameIcontains
		if qContractuserUserLastNameIcontains != "" {
			if err := r.SetQueryParam("contractuser__user__last_name__icontains", qContractuserUserLastNameIcontains); err != nil {
				return err
			}
		}

	}

	if o.ContractuserUserUsername != nil {

		// query param contractuser__user__username
		var qrContractuserUserUsername string
		if o.ContractuserUserUsername != nil {
			qrContractuserUserUsername = *o.ContractuserUserUsername
		}
		qContractuserUserUsername := qrContractuserUserUsername
		if qContractuserUserUsername != "" {
			if err := r.SetQueryParam("contractuser__user__username", qContractuserUserUsername); err != nil {
				return err
			}
		}

	}

	if o.ContractuserUserUsernameContains != nil {

		// query param contractuser__user__username__contains
		var qrContractuserUserUsernameContains string
		if o.ContractuserUserUsernameContains != nil {
			qrContractuserUserUsernameContains = *o.ContractuserUserUsernameContains
		}
		qContractuserUserUsernameContains := qrContractuserUserUsernameContains
		if qContractuserUserUsernameContains != "" {
			if err := r.SetQueryParam("contractuser__user__username__contains", qContractuserUserUsernameContains); err != nil {
				return err
			}
		}

	}

	if o.ContractuserUserUsernameIcontains != nil {

		// query param contractuser__user__username__icontains
		var qrContractuserUserUsernameIcontains string
		if o.ContractuserUserUsernameIcontains != nil {
			qrContractuserUserUsernameIcontains = *o.ContractuserUserUsernameIcontains
		}
		qContractuserUserUsernameIcontains := qrContractuserUserUsernameIcontains
		if qContractuserUserUsernameIcontains != "" {
			if err := r.SetQueryParam("contractuser__user__username__icontains", qContractuserUserUsernameIcontains); err != nil {
				return err
			}
		}

	}

	if o.CustomerCountry != nil {

		// query param customer__country
		var qrCustomerCountry string
		if o.CustomerCountry != nil {
			qrCustomerCountry = *o.CustomerCountry
		}
		qCustomerCountry := qrCustomerCountry
		if qCustomerCountry != "" {
			if err := r.SetQueryParam("customer__country", qCustomerCountry); err != nil {
				return err
			}
		}

	}

	if o.CustomerInternal != nil {

		// query param customer__internal
		var qrCustomerInternal string
		if o.CustomerInternal != nil {
			qrCustomerInternal = *o.CustomerInternal
		}
		qCustomerInternal := qrCustomerInternal
		if qCustomerInternal != "" {
			if err := r.SetQueryParam("customer__internal", qCustomerInternal); err != nil {
				return err
			}
		}

	}

	if o.CustomerName != nil {

		// query param customer__name
		var qrCustomerName string
		if o.CustomerName != nil {
			qrCustomerName = *o.CustomerName
		}
		qCustomerName := qrCustomerName
		if qCustomerName != "" {
			if err := r.SetQueryParam("customer__name", qCustomerName); err != nil {
				return err
			}
		}

	}

	if o.CustomerNameContains != nil {

		// query param customer__name__contains
		var qrCustomerNameContains string
		if o.CustomerNameContains != nil {
			qrCustomerNameContains = *o.CustomerNameContains
		}
		qCustomerNameContains := qrCustomerNameContains
		if qCustomerNameContains != "" {
			if err := r.SetQueryParam("customer__name__contains", qCustomerNameContains); err != nil {
				return err
			}
		}

	}

	if o.CustomerNameIcontains != nil {

		// query param customer__name__icontains
		var qrCustomerNameIcontains string
		if o.CustomerNameIcontains != nil {
			qrCustomerNameIcontains = *o.CustomerNameIcontains
		}
		qCustomerNameIcontains := qrCustomerNameIcontains
		if qCustomerNameIcontains != "" {
			if err := r.SetQueryParam("customer__name__icontains", qCustomerNameIcontains); err != nil {
				return err
			}
		}

	}

	if o.CustomerVatIdentificationNumber != nil {

		// query param customer__vat_identification_number
		var qrCustomerVatIdentificationNumber string
		if o.CustomerVatIdentificationNumber != nil {
			qrCustomerVatIdentificationNumber = *o.CustomerVatIdentificationNumber
		}
		qCustomerVatIdentificationNumber := qrCustomerVatIdentificationNumber
		if qCustomerVatIdentificationNumber != "" {
			if err := r.SetQueryParam("customer__vat_identification_number", qCustomerVatIdentificationNumber); err != nil {
				return err
			}
		}

	}

	if o.Description != nil {

		// query param description
		var qrDescription string
		if o.Description != nil {
			qrDescription = *o.Description
		}
		qDescription := qrDescription
		if qDescription != "" {
			if err := r.SetQueryParam("description", qDescription); err != nil {
				return err
			}
		}

	}

	if o.DescriptionContains != nil {

		// query param description__contains
		var qrDescriptionContains string
		if o.DescriptionContains != nil {
			qrDescriptionContains = *o.DescriptionContains
		}
		qDescriptionContains := qrDescriptionContains
		if qDescriptionContains != "" {
			if err := r.SetQueryParam("description__contains", qDescriptionContains); err != nil {
				return err
			}
		}

	}

	if o.DescriptionIcontains != nil {

		// query param description__icontains
		var qrDescriptionIcontains string
		if o.DescriptionIcontains != nil {
			qrDescriptionIcontains = *o.DescriptionIcontains
		}
		qDescriptionIcontains := qrDescriptionIcontains
		if qDescriptionIcontains != "" {
			if err := r.SetQueryParam("description__icontains", qDescriptionIcontains); err != nil {
				return err
			}
		}

	}

	if o.Label != nil {

		// query param label
		var qrLabel string
		if o.Label != nil {
			qrLabel = *o.Label
		}
		qLabel := qrLabel
		if qLabel != "" {
			if err := r.SetQueryParam("label", qLabel); err != nil {
				return err
			}
		}

	}

	if o.LabelContains != nil {

		// query param label__contains
		var qrLabelContains string
		if o.LabelContains != nil {
			qrLabelContains = *o.LabelContains
		}
		qLabelContains := qrLabelContains
		if qLabelContains != "" {
			if err := r.SetQueryParam("label__contains", qLabelContains); err != nil {
				return err
			}
		}

	}

	if o.LabelIcontains != nil {

		// query param label__icontains
		var qrLabelIcontains string
		if o.LabelIcontains != nil {
			qrLabelIcontains = *o.LabelIcontains
		}
		qLabelIcontains := qrLabelIcontains
		if qLabelIcontains != "" {
			if err := r.SetQueryParam("label__icontains", qLabelIcontains); err != nil {
				return err
			}
		}

	}

	if o.OrderBy != nil {

		// query param order_by
		var qrOrderBy string
		if o.OrderBy != nil {
			qrOrderBy = *o.OrderBy
		}
		qOrderBy := qrOrderBy
		if qOrderBy != "" {
			if err := r.SetQueryParam("order_by", qOrderBy); err != nil {
				return err
			}
		}

	}

	if o.Page != nil {

		// query param page
		var qrPage string
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := qrPage
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if o.PageSize != nil {

		// query param page_size
		var qrPageSize string
		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := qrPageSize
		if qPageSize != "" {
			if err := r.SetQueryParam("page_size", qPageSize); err != nil {
				return err
			}
		}

	}

	if o.PerformanceTypesID != nil {

		// query param performance_types__id
		var qrPerformanceTypesID string
		if o.PerformanceTypesID != nil {
			qrPerformanceTypesID = *o.PerformanceTypesID
		}
		qPerformanceTypesID := qrPerformanceTypesID
		if qPerformanceTypesID != "" {
			if err := r.SetQueryParam("performance_types__id", qPerformanceTypesID); err != nil {
				return err
			}
		}

	}

	if o.PerformanceTypesLabel != nil {

		// query param performance_types__label
		var qrPerformanceTypesLabel string
		if o.PerformanceTypesLabel != nil {
			qrPerformanceTypesLabel = *o.PerformanceTypesLabel
		}
		qPerformanceTypesLabel := qrPerformanceTypesLabel
		if qPerformanceTypesLabel != "" {
			if err := r.SetQueryParam("performance_types__label", qPerformanceTypesLabel); err != nil {
				return err
			}
		}

	}

	if o.PerformanceTypesLabelContains != nil {

		// query param performance_types__label__contains
		var qrPerformanceTypesLabelContains string
		if o.PerformanceTypesLabelContains != nil {
			qrPerformanceTypesLabelContains = *o.PerformanceTypesLabelContains
		}
		qPerformanceTypesLabelContains := qrPerformanceTypesLabelContains
		if qPerformanceTypesLabelContains != "" {
			if err := r.SetQueryParam("performance_types__label__contains", qPerformanceTypesLabelContains); err != nil {
				return err
			}
		}

	}

	if o.PerformanceTypesLabelIcontains != nil {

		// query param performance_types__label__icontains
		var qrPerformanceTypesLabelIcontains string
		if o.PerformanceTypesLabelIcontains != nil {
			qrPerformanceTypesLabelIcontains = *o.PerformanceTypesLabelIcontains
		}
		qPerformanceTypesLabelIcontains := qrPerformanceTypesLabelIcontains
		if qPerformanceTypesLabelIcontains != "" {
			if err := r.SetQueryParam("performance_types__label__icontains", qPerformanceTypesLabelIcontains); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
