// Code generated by go-swagger; DO NOT EDIT.

package contract_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewContractGroupsReadParams creates a new ContractGroupsReadParams object
// with the default values initialized.
func NewContractGroupsReadParams() *ContractGroupsReadParams {
	var ()
	return &ContractGroupsReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewContractGroupsReadParamsWithTimeout creates a new ContractGroupsReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewContractGroupsReadParamsWithTimeout(timeout time.Duration) *ContractGroupsReadParams {
	var ()
	return &ContractGroupsReadParams{

		timeout: timeout,
	}
}

// NewContractGroupsReadParamsWithContext creates a new ContractGroupsReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewContractGroupsReadParamsWithContext(ctx context.Context) *ContractGroupsReadParams {
	var ()
	return &ContractGroupsReadParams{

		Context: ctx,
	}
}

// NewContractGroupsReadParamsWithHTTPClient creates a new ContractGroupsReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewContractGroupsReadParamsWithHTTPClient(client *http.Client) *ContractGroupsReadParams {
	var ()
	return &ContractGroupsReadParams{
		HTTPClient: client,
	}
}

/*ContractGroupsReadParams contains all the parameters to send to the API endpoint
for the contract groups read operation typically these are written to a http.Request
*/
type ContractGroupsReadParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the contract groups read params
func (o *ContractGroupsReadParams) WithTimeout(timeout time.Duration) *ContractGroupsReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the contract groups read params
func (o *ContractGroupsReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the contract groups read params
func (o *ContractGroupsReadParams) WithContext(ctx context.Context) *ContractGroupsReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the contract groups read params
func (o *ContractGroupsReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the contract groups read params
func (o *ContractGroupsReadParams) WithHTTPClient(client *http.Client) *ContractGroupsReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the contract groups read params
func (o *ContractGroupsReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the contract groups read params
func (o *ContractGroupsReadParams) WithID(id string) *ContractGroupsReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the contract groups read params
func (o *ContractGroupsReadParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ContractGroupsReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
