// Code generated by go-swagger; DO NOT EDIT.

package contract_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new contract groups API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for contract groups API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
ContractGroupsList APIs endpoint that allows contract groups to be viewed or edited

API endpoint that allows contract groups to be viewed or edited.
*/
func (a *Client) ContractGroupsList(params *ContractGroupsListParams, authInfo runtime.ClientAuthInfoWriter) (*ContractGroupsListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewContractGroupsListParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "contract_groups_list",
		Method:             "GET",
		PathPattern:        "/api/v1/contract_groups/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ContractGroupsListReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ContractGroupsListOK), nil

}

/*
ContractGroupsRead APIs endpoint that allows contract groups to be viewed or edited

API endpoint that allows contract groups to be viewed or edited.
*/
func (a *Client) ContractGroupsRead(params *ContractGroupsReadParams, authInfo runtime.ClientAuthInfoWriter) (*ContractGroupsReadOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewContractGroupsReadParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "contract_groups_read",
		Method:             "GET",
		PathPattern:        "/api/v1/contract_groups/{id}/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ContractGroupsReadReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ContractGroupsReadOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
