// Code generated by go-swagger; DO NOT EDIT.

package services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewServicesMyLeaveRequestUpdatePartialUpdateParams creates a new ServicesMyLeaveRequestUpdatePartialUpdateParams object
// with the default values initialized.
func NewServicesMyLeaveRequestUpdatePartialUpdateParams() *ServicesMyLeaveRequestUpdatePartialUpdateParams {
	var ()
	return &ServicesMyLeaveRequestUpdatePartialUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewServicesMyLeaveRequestUpdatePartialUpdateParamsWithTimeout creates a new ServicesMyLeaveRequestUpdatePartialUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewServicesMyLeaveRequestUpdatePartialUpdateParamsWithTimeout(timeout time.Duration) *ServicesMyLeaveRequestUpdatePartialUpdateParams {
	var ()
	return &ServicesMyLeaveRequestUpdatePartialUpdateParams{

		timeout: timeout,
	}
}

// NewServicesMyLeaveRequestUpdatePartialUpdateParamsWithContext creates a new ServicesMyLeaveRequestUpdatePartialUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewServicesMyLeaveRequestUpdatePartialUpdateParamsWithContext(ctx context.Context) *ServicesMyLeaveRequestUpdatePartialUpdateParams {
	var ()
	return &ServicesMyLeaveRequestUpdatePartialUpdateParams{

		Context: ctx,
	}
}

// NewServicesMyLeaveRequestUpdatePartialUpdateParamsWithHTTPClient creates a new ServicesMyLeaveRequestUpdatePartialUpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewServicesMyLeaveRequestUpdatePartialUpdateParamsWithHTTPClient(client *http.Client) *ServicesMyLeaveRequestUpdatePartialUpdateParams {
	var ()
	return &ServicesMyLeaveRequestUpdatePartialUpdateParams{
		HTTPClient: client,
	}
}

/*ServicesMyLeaveRequestUpdatePartialUpdateParams contains all the parameters to send to the API endpoint
for the services my leave request update partial update operation typically these are written to a http.Request
*/
type ServicesMyLeaveRequestUpdatePartialUpdateParams struct {

	/*Data*/
	Data ServicesMyLeaveRequestUpdatePartialUpdateBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the services my leave request update partial update params
func (o *ServicesMyLeaveRequestUpdatePartialUpdateParams) WithTimeout(timeout time.Duration) *ServicesMyLeaveRequestUpdatePartialUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the services my leave request update partial update params
func (o *ServicesMyLeaveRequestUpdatePartialUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the services my leave request update partial update params
func (o *ServicesMyLeaveRequestUpdatePartialUpdateParams) WithContext(ctx context.Context) *ServicesMyLeaveRequestUpdatePartialUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the services my leave request update partial update params
func (o *ServicesMyLeaveRequestUpdatePartialUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the services my leave request update partial update params
func (o *ServicesMyLeaveRequestUpdatePartialUpdateParams) WithHTTPClient(client *http.Client) *ServicesMyLeaveRequestUpdatePartialUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the services my leave request update partial update params
func (o *ServicesMyLeaveRequestUpdatePartialUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the services my leave request update partial update params
func (o *ServicesMyLeaveRequestUpdatePartialUpdateParams) WithData(data ServicesMyLeaveRequestUpdatePartialUpdateBody) *ServicesMyLeaveRequestUpdatePartialUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the services my leave request update partial update params
func (o *ServicesMyLeaveRequestUpdatePartialUpdateParams) SetData(data ServicesMyLeaveRequestUpdatePartialUpdateBody) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *ServicesMyLeaveRequestUpdatePartialUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
