// Code generated by go-swagger; DO NOT EDIT.

package services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ServicesMyUserListReader is a Reader for the ServicesMyUserList structure.
type ServicesMyUserListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ServicesMyUserListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewServicesMyUserListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewServicesMyUserListOK creates a ServicesMyUserListOK with default headers values
func NewServicesMyUserListOK() *ServicesMyUserListOK {
	return &ServicesMyUserListOK{}
}

/*ServicesMyUserListOK handles this case with default header values.

ServicesMyUserListOK services my user list o k
*/
type ServicesMyUserListOK struct {
}

func (o *ServicesMyUserListOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/services/my_user/][%d] servicesMyUserListOK ", 200)
}

func (o *ServicesMyUserListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
