// Code generated by go-swagger; DO NOT EDIT.

package companies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCompaniesReadParams creates a new CompaniesReadParams object
// with the default values initialized.
func NewCompaniesReadParams() *CompaniesReadParams {
	var ()
	return &CompaniesReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCompaniesReadParamsWithTimeout creates a new CompaniesReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCompaniesReadParamsWithTimeout(timeout time.Duration) *CompaniesReadParams {
	var ()
	return &CompaniesReadParams{

		timeout: timeout,
	}
}

// NewCompaniesReadParamsWithContext creates a new CompaniesReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewCompaniesReadParamsWithContext(ctx context.Context) *CompaniesReadParams {
	var ()
	return &CompaniesReadParams{

		Context: ctx,
	}
}

// NewCompaniesReadParamsWithHTTPClient creates a new CompaniesReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCompaniesReadParamsWithHTTPClient(client *http.Client) *CompaniesReadParams {
	var ()
	return &CompaniesReadParams{
		HTTPClient: client,
	}
}

/*CompaniesReadParams contains all the parameters to send to the API endpoint
for the companies read operation typically these are written to a http.Request
*/
type CompaniesReadParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the companies read params
func (o *CompaniesReadParams) WithTimeout(timeout time.Duration) *CompaniesReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the companies read params
func (o *CompaniesReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the companies read params
func (o *CompaniesReadParams) WithContext(ctx context.Context) *CompaniesReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the companies read params
func (o *CompaniesReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the companies read params
func (o *CompaniesReadParams) WithHTTPClient(client *http.Client) *CompaniesReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the companies read params
func (o *CompaniesReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the companies read params
func (o *CompaniesReadParams) WithID(id string) *CompaniesReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the companies read params
func (o *CompaniesReadParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CompaniesReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
