// Code generated by go-swagger; DO NOT EDIT.

package companies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// CompaniesListReader is a Reader for the CompaniesList structure.
type CompaniesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CompaniesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCompaniesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCompaniesListOK creates a CompaniesListOK with default headers values
func NewCompaniesListOK() *CompaniesListOK {
	return &CompaniesListOK{}
}

/*CompaniesListOK handles this case with default header values.

CompaniesListOK companies list o k
*/
type CompaniesListOK struct {
}

func (o *CompaniesListOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/companies/][%d] companiesListOK ", 200)
}

func (o *CompaniesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
