// Code generated by go-swagger; DO NOT EDIT.

package whereabouts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new whereabouts API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for whereabouts API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
WhereaboutsList APIs endpoint that allows whereabouts to be viewed or edited

API endpoint that allows whereabouts to be viewed or edited.
*/
func (a *Client) WhereaboutsList(params *WhereaboutsListParams, authInfo runtime.ClientAuthInfoWriter) (*WhereaboutsListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewWhereaboutsListParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "whereabouts_list",
		Method:             "GET",
		PathPattern:        "/api/v1/whereabouts/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &WhereaboutsListReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*WhereaboutsListOK), nil

}

/*
WhereaboutsRead APIs endpoint that allows whereabouts to be viewed or edited

API endpoint that allows whereabouts to be viewed or edited.
*/
func (a *Client) WhereaboutsRead(params *WhereaboutsReadParams, authInfo runtime.ClientAuthInfoWriter) (*WhereaboutsReadOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewWhereaboutsReadParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "whereabouts_read",
		Method:             "GET",
		PathPattern:        "/api/v1/whereabouts/{id}/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &WhereaboutsReadReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*WhereaboutsReadOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
