// Code generated by go-swagger; DO NOT EDIT.

package whereabouts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// WhereaboutsListReader is a Reader for the WhereaboutsList structure.
type WhereaboutsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WhereaboutsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewWhereaboutsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewWhereaboutsListOK creates a WhereaboutsListOK with default headers values
func NewWhereaboutsListOK() *WhereaboutsListOK {
	return &WhereaboutsListOK{}
}

/*WhereaboutsListOK handles this case with default header values.

WhereaboutsListOK whereabouts list o k
*/
type WhereaboutsListOK struct {
}

func (o *WhereaboutsListOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/whereabouts/][%d] whereaboutsListOK ", 200)
}

func (o *WhereaboutsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
