// Code generated by go-swagger; DO NOT EDIT.

package whereabouts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// WhereaboutsReadReader is a Reader for the WhereaboutsRead structure.
type WhereaboutsReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WhereaboutsReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewWhereaboutsReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewWhereaboutsReadOK creates a WhereaboutsReadOK with default headers values
func NewWhereaboutsReadOK() *WhereaboutsReadOK {
	return &WhereaboutsReadOK{}
}

/*WhereaboutsReadOK handles this case with default header values.

WhereaboutsReadOK whereabouts read o k
*/
type WhereaboutsReadOK struct {
}

func (o *WhereaboutsReadOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/whereabouts/{id}/][%d] whereaboutsReadOK ", 200)
}

func (o *WhereaboutsReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
