// Code generated by go-swagger; DO NOT EDIT.

package my_performances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewMyPerformancesReadParams creates a new MyPerformancesReadParams object
// with the default values initialized.
func NewMyPerformancesReadParams() *MyPerformancesReadParams {
	var ()
	return &MyPerformancesReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMyPerformancesReadParamsWithTimeout creates a new MyPerformancesReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMyPerformancesReadParamsWithTimeout(timeout time.Duration) *MyPerformancesReadParams {
	var ()
	return &MyPerformancesReadParams{

		timeout: timeout,
	}
}

// NewMyPerformancesReadParamsWithContext creates a new MyPerformancesReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewMyPerformancesReadParamsWithContext(ctx context.Context) *MyPerformancesReadParams {
	var ()
	return &MyPerformancesReadParams{

		Context: ctx,
	}
}

// NewMyPerformancesReadParamsWithHTTPClient creates a new MyPerformancesReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMyPerformancesReadParamsWithHTTPClient(client *http.Client) *MyPerformancesReadParams {
	var ()
	return &MyPerformancesReadParams{
		HTTPClient: client,
	}
}

/*MyPerformancesReadParams contains all the parameters to send to the API endpoint
for the my performances read operation typically these are written to a http.Request
*/
type MyPerformancesReadParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the my performances read params
func (o *MyPerformancesReadParams) WithTimeout(timeout time.Duration) *MyPerformancesReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the my performances read params
func (o *MyPerformancesReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the my performances read params
func (o *MyPerformancesReadParams) WithContext(ctx context.Context) *MyPerformancesReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the my performances read params
func (o *MyPerformancesReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the my performances read params
func (o *MyPerformancesReadParams) WithHTTPClient(client *http.Client) *MyPerformancesReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the my performances read params
func (o *MyPerformancesReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the my performances read params
func (o *MyPerformancesReadParams) WithID(id string) *MyPerformancesReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the my performances read params
func (o *MyPerformancesReadParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *MyPerformancesReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
