// Code generated by go-swagger; DO NOT EDIT.

package my_performances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// MyPerformancesActivityPartialUpdateReader is a Reader for the MyPerformancesActivityPartialUpdate structure.
type MyPerformancesActivityPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MyPerformancesActivityPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewMyPerformancesActivityPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewMyPerformancesActivityPartialUpdateOK creates a MyPerformancesActivityPartialUpdateOK with default headers values
func NewMyPerformancesActivityPartialUpdateOK() *MyPerformancesActivityPartialUpdateOK {
	return &MyPerformancesActivityPartialUpdateOK{}
}

/*MyPerformancesActivityPartialUpdateOK handles this case with default header values.

MyPerformancesActivityPartialUpdateOK my performances activity partial update o k
*/
type MyPerformancesActivityPartialUpdateOK struct {
}

func (o *MyPerformancesActivityPartialUpdateOK) Error() string {
	return fmt.Sprintf("[PATCH /api/v1/my_performances/activity/{id}/][%d] myPerformancesActivityPartialUpdateOK ", 200)
}

func (o *MyPerformancesActivityPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*MyPerformancesActivityPartialUpdateBody my performances activity partial update body
swagger:model MyPerformancesActivityPartialUpdateBody
*/

type MyPerformancesActivityPartialUpdateBody struct {

	// contract
	Contract string `json:"contract,omitempty"`

	// contract role
	ContractRole string `json:"contract_role,omitempty"`

	// day
	Day int64 `json:"day,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// duration
	Duration float64 `json:"duration,omitempty"`

	// performance type
	PerformanceType string `json:"performance_type,omitempty"`

	// redmine id
	RedmineID string `json:"redmine_id,omitempty"`

	// timesheet
	Timesheet string `json:"timesheet,omitempty"`
}

/* polymorph MyPerformancesActivityPartialUpdateBody contract false */

/* polymorph MyPerformancesActivityPartialUpdateBody contract_role false */

/* polymorph MyPerformancesActivityPartialUpdateBody day false */

/* polymorph MyPerformancesActivityPartialUpdateBody description false */

/* polymorph MyPerformancesActivityPartialUpdateBody duration false */

/* polymorph MyPerformancesActivityPartialUpdateBody performance_type false */

/* polymorph MyPerformancesActivityPartialUpdateBody redmine_id false */

/* polymorph MyPerformancesActivityPartialUpdateBody timesheet false */

// MarshalBinary interface implementation
func (o *MyPerformancesActivityPartialUpdateBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *MyPerformancesActivityPartialUpdateBody) UnmarshalBinary(b []byte) error {
	var res MyPerformancesActivityPartialUpdateBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
