// Code generated by go-swagger; DO NOT EDIT.

package my_performances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewMyPerformancesStandbyCreateParams creates a new MyPerformancesStandbyCreateParams object
// with the default values initialized.
func NewMyPerformancesStandbyCreateParams() *MyPerformancesStandbyCreateParams {
	var ()
	return &MyPerformancesStandbyCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMyPerformancesStandbyCreateParamsWithTimeout creates a new MyPerformancesStandbyCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMyPerformancesStandbyCreateParamsWithTimeout(timeout time.Duration) *MyPerformancesStandbyCreateParams {
	var ()
	return &MyPerformancesStandbyCreateParams{

		timeout: timeout,
	}
}

// NewMyPerformancesStandbyCreateParamsWithContext creates a new MyPerformancesStandbyCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewMyPerformancesStandbyCreateParamsWithContext(ctx context.Context) *MyPerformancesStandbyCreateParams {
	var ()
	return &MyPerformancesStandbyCreateParams{

		Context: ctx,
	}
}

// NewMyPerformancesStandbyCreateParamsWithHTTPClient creates a new MyPerformancesStandbyCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMyPerformancesStandbyCreateParamsWithHTTPClient(client *http.Client) *MyPerformancesStandbyCreateParams {
	var ()
	return &MyPerformancesStandbyCreateParams{
		HTTPClient: client,
	}
}

/*MyPerformancesStandbyCreateParams contains all the parameters to send to the API endpoint
for the my performances standby create operation typically these are written to a http.Request
*/
type MyPerformancesStandbyCreateParams struct {

	/*Data*/
	Data MyPerformancesStandbyCreateBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the my performances standby create params
func (o *MyPerformancesStandbyCreateParams) WithTimeout(timeout time.Duration) *MyPerformancesStandbyCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the my performances standby create params
func (o *MyPerformancesStandbyCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the my performances standby create params
func (o *MyPerformancesStandbyCreateParams) WithContext(ctx context.Context) *MyPerformancesStandbyCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the my performances standby create params
func (o *MyPerformancesStandbyCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the my performances standby create params
func (o *MyPerformancesStandbyCreateParams) WithHTTPClient(client *http.Client) *MyPerformancesStandbyCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the my performances standby create params
func (o *MyPerformancesStandbyCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the my performances standby create params
func (o *MyPerformancesStandbyCreateParams) WithData(data MyPerformancesStandbyCreateBody) *MyPerformancesStandbyCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the my performances standby create params
func (o *MyPerformancesStandbyCreateParams) SetData(data MyPerformancesStandbyCreateBody) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *MyPerformancesStandbyCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
