// Code generated by go-swagger; DO NOT EDIT.

package my_performances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// MyPerformancesStandbyReadReader is a Reader for the MyPerformancesStandbyRead structure.
type MyPerformancesStandbyReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MyPerformancesStandbyReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewMyPerformancesStandbyReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewMyPerformancesStandbyReadOK creates a MyPerformancesStandbyReadOK with default headers values
func NewMyPerformancesStandbyReadOK() *MyPerformancesStandbyReadOK {
	return &MyPerformancesStandbyReadOK{}
}

/*MyPerformancesStandbyReadOK handles this case with default header values.

MyPerformancesStandbyReadOK my performances standby read o k
*/
type MyPerformancesStandbyReadOK struct {
}

func (o *MyPerformancesStandbyReadOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/my_performances/standby/{id}/][%d] myPerformancesStandbyReadOK ", 200)
}

func (o *MyPerformancesStandbyReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
