// Code generated by go-swagger; DO NOT EDIT.

package my_performances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// MyPerformancesStandbyListReader is a Reader for the MyPerformancesStandbyList structure.
type MyPerformancesStandbyListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MyPerformancesStandbyListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewMyPerformancesStandbyListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewMyPerformancesStandbyListOK creates a MyPerformancesStandbyListOK with default headers values
func NewMyPerformancesStandbyListOK() *MyPerformancesStandbyListOK {
	return &MyPerformancesStandbyListOK{}
}

/*MyPerformancesStandbyListOK handles this case with default header values.

MyPerformancesStandbyListOK my performances standby list o k
*/
type MyPerformancesStandbyListOK struct {
}

func (o *MyPerformancesStandbyListOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/my_performances/standby/][%d] myPerformancesStandbyListOK ", 200)
}

func (o *MyPerformancesStandbyListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
