// Code generated by go-swagger; DO NOT EDIT.

package my_performances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewMyPerformancesStandbyPartialUpdateParams creates a new MyPerformancesStandbyPartialUpdateParams object
// with the default values initialized.
func NewMyPerformancesStandbyPartialUpdateParams() *MyPerformancesStandbyPartialUpdateParams {
	var ()
	return &MyPerformancesStandbyPartialUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMyPerformancesStandbyPartialUpdateParamsWithTimeout creates a new MyPerformancesStandbyPartialUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMyPerformancesStandbyPartialUpdateParamsWithTimeout(timeout time.Duration) *MyPerformancesStandbyPartialUpdateParams {
	var ()
	return &MyPerformancesStandbyPartialUpdateParams{

		timeout: timeout,
	}
}

// NewMyPerformancesStandbyPartialUpdateParamsWithContext creates a new MyPerformancesStandbyPartialUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewMyPerformancesStandbyPartialUpdateParamsWithContext(ctx context.Context) *MyPerformancesStandbyPartialUpdateParams {
	var ()
	return &MyPerformancesStandbyPartialUpdateParams{

		Context: ctx,
	}
}

// NewMyPerformancesStandbyPartialUpdateParamsWithHTTPClient creates a new MyPerformancesStandbyPartialUpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMyPerformancesStandbyPartialUpdateParamsWithHTTPClient(client *http.Client) *MyPerformancesStandbyPartialUpdateParams {
	var ()
	return &MyPerformancesStandbyPartialUpdateParams{
		HTTPClient: client,
	}
}

/*MyPerformancesStandbyPartialUpdateParams contains all the parameters to send to the API endpoint
for the my performances standby partial update operation typically these are written to a http.Request
*/
type MyPerformancesStandbyPartialUpdateParams struct {

	/*Data*/
	Data MyPerformancesStandbyPartialUpdateBody
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the my performances standby partial update params
func (o *MyPerformancesStandbyPartialUpdateParams) WithTimeout(timeout time.Duration) *MyPerformancesStandbyPartialUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the my performances standby partial update params
func (o *MyPerformancesStandbyPartialUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the my performances standby partial update params
func (o *MyPerformancesStandbyPartialUpdateParams) WithContext(ctx context.Context) *MyPerformancesStandbyPartialUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the my performances standby partial update params
func (o *MyPerformancesStandbyPartialUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the my performances standby partial update params
func (o *MyPerformancesStandbyPartialUpdateParams) WithHTTPClient(client *http.Client) *MyPerformancesStandbyPartialUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the my performances standby partial update params
func (o *MyPerformancesStandbyPartialUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the my performances standby partial update params
func (o *MyPerformancesStandbyPartialUpdateParams) WithData(data MyPerformancesStandbyPartialUpdateBody) *MyPerformancesStandbyPartialUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the my performances standby partial update params
func (o *MyPerformancesStandbyPartialUpdateParams) SetData(data MyPerformancesStandbyPartialUpdateBody) {
	o.Data = data
}

// WithID adds the id to the my performances standby partial update params
func (o *MyPerformancesStandbyPartialUpdateParams) WithID(id string) *MyPerformancesStandbyPartialUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the my performances standby partial update params
func (o *MyPerformancesStandbyPartialUpdateParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *MyPerformancesStandbyPartialUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
