// Code generated by go-swagger; DO NOT EDIT.

package my_performances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewMyPerformancesActivityUpdateParams creates a new MyPerformancesActivityUpdateParams object
// with the default values initialized.
func NewMyPerformancesActivityUpdateParams() *MyPerformancesActivityUpdateParams {
	var ()
	return &MyPerformancesActivityUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMyPerformancesActivityUpdateParamsWithTimeout creates a new MyPerformancesActivityUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMyPerformancesActivityUpdateParamsWithTimeout(timeout time.Duration) *MyPerformancesActivityUpdateParams {
	var ()
	return &MyPerformancesActivityUpdateParams{

		timeout: timeout,
	}
}

// NewMyPerformancesActivityUpdateParamsWithContext creates a new MyPerformancesActivityUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewMyPerformancesActivityUpdateParamsWithContext(ctx context.Context) *MyPerformancesActivityUpdateParams {
	var ()
	return &MyPerformancesActivityUpdateParams{

		Context: ctx,
	}
}

// NewMyPerformancesActivityUpdateParamsWithHTTPClient creates a new MyPerformancesActivityUpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMyPerformancesActivityUpdateParamsWithHTTPClient(client *http.Client) *MyPerformancesActivityUpdateParams {
	var ()
	return &MyPerformancesActivityUpdateParams{
		HTTPClient: client,
	}
}

/*MyPerformancesActivityUpdateParams contains all the parameters to send to the API endpoint
for the my performances activity update operation typically these are written to a http.Request
*/
type MyPerformancesActivityUpdateParams struct {

	/*Data*/
	Data MyPerformancesActivityUpdateBody
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the my performances activity update params
func (o *MyPerformancesActivityUpdateParams) WithTimeout(timeout time.Duration) *MyPerformancesActivityUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the my performances activity update params
func (o *MyPerformancesActivityUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the my performances activity update params
func (o *MyPerformancesActivityUpdateParams) WithContext(ctx context.Context) *MyPerformancesActivityUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the my performances activity update params
func (o *MyPerformancesActivityUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the my performances activity update params
func (o *MyPerformancesActivityUpdateParams) WithHTTPClient(client *http.Client) *MyPerformancesActivityUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the my performances activity update params
func (o *MyPerformancesActivityUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the my performances activity update params
func (o *MyPerformancesActivityUpdateParams) WithData(data MyPerformancesActivityUpdateBody) *MyPerformancesActivityUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the my performances activity update params
func (o *MyPerformancesActivityUpdateParams) SetData(data MyPerformancesActivityUpdateBody) {
	o.Data = data
}

// WithID adds the id to the my performances activity update params
func (o *MyPerformancesActivityUpdateParams) WithID(id string) *MyPerformancesActivityUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the my performances activity update params
func (o *MyPerformancesActivityUpdateParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *MyPerformancesActivityUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
