// Code generated by go-swagger; DO NOT EDIT.

package leave_types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLeaveTypesReadParams creates a new LeaveTypesReadParams object
// with the default values initialized.
func NewLeaveTypesReadParams() *LeaveTypesReadParams {
	var ()
	return &LeaveTypesReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLeaveTypesReadParamsWithTimeout creates a new LeaveTypesReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLeaveTypesReadParamsWithTimeout(timeout time.Duration) *LeaveTypesReadParams {
	var ()
	return &LeaveTypesReadParams{

		timeout: timeout,
	}
}

// NewLeaveTypesReadParamsWithContext creates a new LeaveTypesReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewLeaveTypesReadParamsWithContext(ctx context.Context) *LeaveTypesReadParams {
	var ()
	return &LeaveTypesReadParams{

		Context: ctx,
	}
}

// NewLeaveTypesReadParamsWithHTTPClient creates a new LeaveTypesReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewLeaveTypesReadParamsWithHTTPClient(client *http.Client) *LeaveTypesReadParams {
	var ()
	return &LeaveTypesReadParams{
		HTTPClient: client,
	}
}

/*LeaveTypesReadParams contains all the parameters to send to the API endpoint
for the leave types read operation typically these are written to a http.Request
*/
type LeaveTypesReadParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the leave types read params
func (o *LeaveTypesReadParams) WithTimeout(timeout time.Duration) *LeaveTypesReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the leave types read params
func (o *LeaveTypesReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the leave types read params
func (o *LeaveTypesReadParams) WithContext(ctx context.Context) *LeaveTypesReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the leave types read params
func (o *LeaveTypesReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the leave types read params
func (o *LeaveTypesReadParams) WithHTTPClient(client *http.Client) *LeaveTypesReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the leave types read params
func (o *LeaveTypesReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the leave types read params
func (o *LeaveTypesReadParams) WithID(id string) *LeaveTypesReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the leave types read params
func (o *LeaveTypesReadParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *LeaveTypesReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
